Improve error messages from compliance fetcher
inspec/inspec pull request #1126
Opened 2016-09-22 13:03 UTC by stevendanna

Signed-off-by: Steven Danna <steve@chef.io>

2016-09-22 13:27 UTC, chris-rock commented
I am not convinced that a fetcher should exit the application. It may throw an exception, but it should never exit the application. If used as a library (as in audit cookbook), the fetcher is not executed as cli application. From my perspective only the CLI application should decide if an exit code should be thrown or not

2016-09-22 13:28 UTC, chris-rock commented on lib/inspec/ui.rb
> +      exit(1)
I strongly advice against to exit application from an internal method.

2016-09-22 13:29 UTC, chris-rock commented on lib/bundles/inspec-compliance/target.rb
> +        Inspec::UI.exit_with_error <<EOF
Its a great idea to add better information about an error, but that should be encapsulated in exceptions

2016-09-22 13:29 UTC, chris-rock requested changes

2016-09-22 13:32 UTC, stevendanna commented
@chris-rock Yeah, I am not thrilled with exiting from here either.  One of the issues with the exception is not dumping the stack trace which obscures the error message.

2016-09-23 09:01 UTC, stevendanna commented
Updated pre code review

2016-09-25 23:33 UTC, chris-rock approved these changes

2016-09-26 00:05 UTC, merged