Add FreeBSD support for ZFS datasets and pools
inspec/inspec pull request #1501
Opened 2017-02-21 17:17 UTC by jbenden

The following new resources have been added; however, they presently only support FreeBSD and similar.

* `zfs_dataset`: tests if a named ZFS dataset is present and/or has certain properties.
* `zfs_pool`: tests if a named ZFS pool is present and/or has certain properties.

The `mount` resource has been refactored to include support for FreeBSD too.

2017-02-21 22:27 UTC, adamleff requested changes
@jbenden Thanks for your contribution! I'm a huge fan of ZFS... used it a lot on OmniOS at my last job... so adding ZFS support fills me with glee. :)

I added a few comments, and we should add some unit tests to this with some mocked output for all the items changed/added (i.e. BSD mounts, ZFS pools, and ZFS datasets). I'd be happy to help you navigate that process if you need any assistance.

2017-02-21 22:27 UTC, adamleff commented on lib/resources/mount.rb
> +    include MountParser
This is probably a good time to rename this to `LinuxMountParser` to avoid any confusion.

2017-02-21 22:27 UTC, adamleff commented on lib/resources/mount.rb
> +  end
Should we add a default `#parse_mount_options` method here that `raise`s an exception to make it clear for future users that the method is required?

2017-02-21 22:27 UTC, adamleff commented on lib/resources/zfs_dataset.rb
> +      return skip_resource 'The `zfs_dataset` resource is not supported on your OS yet.' if !inspec.os.bsd?
We don't need to account for it in this PR, but I suspect this resource would work OK as-is on Solaris and any Linux that is using ZFS-on-Linux too, with the small exception of the actual ZFS binary paths may be different. This is worth some investigation.

2017-02-22 17:43 UTC, jbenden commented
Hello Adam,

I have made all requested modifications; with the exception of supporting Solaris and Linux ZFS. If you have access to either of these operating systems (especially Solaris) I simply need the binary path locations. I am positive this would work with Solaris, but am not sure where the required binaries are... I did see that Linux places them in `/usr/sbin`, but do not know if the output is exactly the same...

2017-02-23 13:22 UTC, chris-rock commented on lib/resources/zfs_dataset.rb
> +      return skip_resource 'The `zfs_dataset` resource is not supported on your OS yet.' if !inspec.os.bsd?
Would love to see the Solaris support for this as well!

2017-02-24 22:06 UTC, adamleff approved these changes

2017-02-24 22:07 UTC, adamleff commented
@chris-rock I think we should accept this as-is and open an enhancement issue for the backlog to extend this to Solaris-variants and even perhaps Linux-on-ZFS users. But since the contributor doesn't have access to a Solaris-based machine, it seems reasonable to accept as-is. Thoughts?

2017-02-24 23:02 UTC, chris-rock commented
I agree with you @adamleff

2017-02-24 23:03 UTC, chris-rock approved these changes

2017-03-01 18:06 UTC, merged

2017-03-01 18:06 UTC, adamleff commented
@jbenden thanks again for this contribution!