Added oracle linux to rhel platform section of 'service' resource.
inspec/inspec pull request #1511
Opened 2017-02-24 03:48 UTC by carldjohnston

Tests currently skipping over 'service' resource on oracle linux. 

Broken when chef/train was fixed to detect oracle linux correctly.

2017-02-24 10:51 UTC, chris-rock commented on lib/resources/service.rb
> +      elsif %w{redhat fedora centos oracle}.include?(platform)
maybe we spit this and support more redhat systems?

```
elsif os.redhat?
  if os[:release].to_i >= 7
    Systemd.new(inspec, service_ctl)
  else
    SysV.new(inspec, service_ctl || '/sbin/service')
  end
elsif %w{fedora}.include?(platform)
  if os[:release].to_i >= 15
    Systemd.new(inspec, service_ctl)
  else
    SysV.new(inspec, service_ctl || '/sbin/service')
  end
```

to support https://github.com/chef/train/blob/master/lib/train/extras/os_detect_linux.rb#L17

2017-02-24 22:08 UTC, adamleff commented on lib/resources/service.rb
> +      elsif %w{redhat fedora centos oracle}.include?(platform)
I'm in favor of @chris-rock's suggestion as well.

2017-02-28 11:26 UTC, chris-rock commented
@carldjohnston Anything we can help you with to get the support for oracle linux in?

2017-03-01 01:03 UTC, carldjohnston commented
Hi @chris-rock, thanks for the prod - just finding time to progress these :)

I like you're suggestions, new commit shows this new approach.

2017-03-01 18:06 UTC, chris-rock approved these changes
Thank you @carldjohnston

2017-03-01 18:11 UTC, chris-rock requested changes
I forgot wrlinux. @carldjohnston Can you please update once again. I apologize for the extra work. I like the split between fedora and redhat though.

2017-03-01 18:11 UTC, chris-rock commented on lib/resources/service.rb
> +      elsif os.redhat?
We need to go with `%w{redhat fedora centos oracle}.include?(platform)`

2017-03-01 21:58 UTC, carldjohnston commented on lib/resources/service.rb
> +      elsif os.redhat?
Thanks @chris-rock, I've reverted to the previous commit - messy but it works :)

2017-03-02 02:27 UTC, zetan503 commented
I have this problem, all Oracle Linux systems, and inspec service is not supported. When will this be generally available, or is there a workaround?

2017-03-02 08:44 UTC, chris-rock commented
@carldjohnston Can you do me a favor? We do not need the revert in our history. We need to rebase your branch on latest master and remove the 2 of the 3 commits. You can fix that with the following commands:
```
➜  inspec git:(oracle-linux-service-resource) ✗ git checkout master
Switched to branch 'master'
➜  inspec git:(master) git remote add inspec https://github.com/chef/inspec.git
➜  inspec git:(master) ✗ git pull inspec master
From https://github.com/chef/inspec
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> inspec/master
Already up-to-date.
➜  inspec git:(master) ✗ git checkout oracle-linux-service-resource
Switched to branch 'oracle-linux-service-resource'
Your branch is up-to-date with 'carldjohnston/oracle-linux-service-resource'.
➜  inspec git:(oracle-linux-service-resource) ✗ git rebase master
First, rewinding head to replay your work on top of it...
Applying: Added oracle linux to rhel platform section.
Applying: Split rhel / fedora to support more redhat systems (via chef/train)
Applying: Revert "Split rhel / fedora to support more redhat systems (via chef/train)"
➜  inspec git:(oracle-linux-service-resource) ✗ git reset HEAD~2
➜  inspec git:(oracle-linux-service-resource) ✗ git push origin oracle-linux-service-resource -f
```

Please ensure that the git history is alright before you force push to github.

2017-03-02 11:11 UTC, carldjohnston commented
Hi @chris-rock, thanks for the instruction, very cool - you learn something new every day!

I've rebased and pushed up the cleaned up repo.

2017-03-02 11:12 UTC, chris-rock approved these changes

2017-03-02 11:14 UTC, chris-rock commented
cc @adamleff

2017-03-02 12:00 UTC, adamleff approved these changes

2017-03-02 12:00 UTC, adamleff commented
Nice work, @carldjohnston! Thanks for working with us on this contribution.

2017-03-02 12:00 UTC, merged