WIP - DO NOT MERGE
inspec/inspec pull request #1512
Opened 2017-02-24 04:47 UTC by hannah-radish

- Added banner for webinars (present and future)
- CSS support for IE10, IE11, Edge
- Fixed URL bug for demo

- MORE STUFF IN PROGRESS. Stay tuned for next commit

2017-02-24 11:07 UTC, chris-rock commented
fixes #1440
fixes #1420
fixes #1465
fixes #1421
fixes #1437
fixes #1226
fixes #1494
fixes #1495

2017-03-03 16:30 UTC, adamleff requested changes
I'm not frontend-smart enough to thoroughly review the CSS changes, but I did test things locally and they looked fine.

I'd like to see URLs be relative (so no hard-coding of `http://inspec.io`) if at all possible to make testing locally and in acceptance environments easier/possible.

Other than that, just some small changes that we should address before releasing.

2017-03-03 16:30 UTC, adamleff commented on www/source/docs/index.html.slim
> +      a.btn.try-demo href="http://inspec.io/tutorial" Try the Demo
Can we make this a relative URL (i.e. `href="/tutorial"`) so it works in local/acceptance environments?

2017-03-03 16:30 UTC, adamleff commented on www/source/downloads.html.slim
> +  location.replace("http://downloads.chef.io");
Should this be `http://downloads.chef.io/inspec`?

2017-03-03 16:30 UTC, adamleff commented on www/source/index.html.slim
> +    a href="https://events.chef.io/events/testing-at-the-edges/"  View the Event
I think this event on March 1 and has come-and-gone... we probably need to put a new event here or perhaps put the surprise code example back.

2017-03-03 16:30 UTC, adamleff commented on www/source/index.html.slim
> +          a.btn.strict-right.t-white.try-demo.mobile-hide href="http://inspec.io/tutorial" Try the Demo
Same comment as above - can we make this a relative URL instead of a direct URL?

2017-03-03 16:30 UTC, adamleff commented on www/source/index.html.slim
> +          a.btn.strict-right.t-white.try-demo.mobile-hide href="http://inspec.io/tutorial" Try the Demo
Same comment re: relative URL.

2017-03-03 16:30 UTC, adamleff commented on www/source/layouts/_footer.slim
> +      a.btn.t-white.try-demo.hide-for-small-only href="http://inspec.io/tutorial" Try the Demo
Same comment re: relative URL.

2017-03-03 16:30 UTC, adamleff commented on www/source/layouts/_nav.slim
> +        a.btn.try-demo href="http://inspec.io/tutorial" Try the Demo
Same comment re: relative URL.

2017-03-03 20:05 UTC, adamleff commented on www/source/docs/index.html.slim
> +      a.btn.try-demo href="http://inspec.io/tutorial" Try the Demo
Looks like one absolute-to-relative URL change missed.

2017-03-03 20:06 UTC, adamleff commented
@hannah-radish looks like one URL change still needed, but otherwise looks good. I'm happy to approve once we get the DCO bot happy. Let me know if you need help with that.

2017-03-04 01:53 UTC, hannah-radish commented
@adamleff okay, fixed the docs link for demo and DCO.

2017-03-05 23:26 UTC, adamleff approved these changes

2017-03-05 23:27 UTC, adamleff commented
Looks great, @hannah-radish - I'm merging now, feel free to push live whenever you're ready, or let me know if you need me to do it.

2017-03-05 23:27 UTC, merged