Avoid connection timeout of "inspec version"
inspec/inspec pull request #1538
Opened 2017-03-05 03:46 UTC by makotots

Fixes https://github.com/chef/inspec/issues/1537 
Signed-off-by: Makoto Nozaki <makoto.nozaki@twosigma.com>

2017-03-05 03:48 UTC, makotots commented
Note: The next line, `http.read_timeout = 0.5` could be moved up to the same level for consistency.

2017-03-05 23:32 UTC, adamleff requested changes
@makotots thank you so much for this PR! I agree that keeping the definition of the options at the same level for consistency is the right thing to do. Would you mind pushing up a new commit with that change? Then I'll be happy to get this approved.

2017-03-05 23:32 UTC, adamleff commented on lib/utils/latest_version.rb
>        http.read_timeout = 0.5
I agree with your comment that this should be moved up to the `#start` opts for consistency. Thank you for suggesting it!

2017-03-06 08:57 UTC, chris-rock approved these changes
Thank you @makotots and @adamleff This is a great improvement.

2017-03-06 16:23 UTC, adamleff approved these changes

2017-03-06 16:23 UTC, adamleff commented
Great work, @makotots! Thank you for your contribution!

2017-03-06 16:23 UTC, merged