WIP: x509_certificate and key_rsa resource
inspec/inspec pull request #1567
Opened 2017-03-15 22:35 UTC by chris-rock

This PR fixes #1459

Now you can define tests like:

```
describe x509_certificate('trials/x509/cert.pem') do
  it { should be_certificate }
  it { should be_valid }
  its('signature_algorithm') { should eq 'sha1WithRSAEncryption' }
  its('validity_in_days') { should_not be < 100 }
  its('validity_in_days') { should be >= 100 }
  its('subject') { should eq '/C=DE/ST=Berlin/L=Berlin/O=InSpec/OU=Chef Software, Inc/CN=inspec.io/emailAddress=support@chef.io' }
  its('issuer') { should eq '/C=DE/ST=Berlin/L=Berlin/O=InSpec/OU=Chef Software, Inc/CN=inspec.io/emailAddress=support@chef.io' }
  its('email') { should_not be_empty }
  its('email') { should eq 'support@chef.io' }
  its('keylength') { should be >= 2048 }
end

describe x509_certificate('trials/x509/x505.md') do
  it { should_not be_certificate }
end

describe key_rsa('trials/x509/key.pem', 'passphrase') do
  it { should be_valid }
  it { should be_private }
  it { should be_public }
end
```

which will result in:

```
b inspec exec trials/x509.rb

Profile: tests from trials/x509.rb
Version: (not specified)
Target:  local://

  x509_certificate should
     ✔  be certificate
     ✔  be valid
     ✔  should eq "sha1WithRSAEncryption"
     ✔  should not be < 100
     ✔  should be >= 100
     ✔  should eq "/C=DE/ST=Berlin/L=Berlin/O=InSpec/OU=Chef Software, Inc/CN=inspec.io/emailAddress=support@chef.io"
     ✔  should eq "/C=DE/ST=Berlin/L=Berlin/O=InSpec/OU=Chef Software, Inc/CN=inspec.io/emailAddress=support@chef.io"
     ✔  should not be empty
     ✔  should eq "support@chef.io"
     ✔  should be >= 2048
  x509_certificate should
     ✔  not be certificate
  key_rsa should
     ✔  be valid
     ✔  be private
     ✔  be public

Test Summary: 14 successful, 0 failures, 0 skipped
```

TODO:
 * [ ] integration tests
 * [ ] unit tests

2017-03-16 01:09 UTC, aaronlippold commented on lib/resources/key_rsa.rb
> +    end
So are we saying that a certificate is valid if it is public? I think we may need to refine what we mean by 'valid' just so it is clear. In the DoD sense, a key is 'valid' is it was issues and signed by an approved known trusted CA - i.e. one of the valid root or intermediate authorities.

2017-03-16 01:18 UTC, aaronlippold commented on lib/resources/x509.rb
> +    # @see https://tools.ietf.org/html/rfc5280#page-23
Small thing, If possible I would like to be able to say, its(... OU, CN, O, L, or CN ) { should match \*DOD*\}

2017-03-16 01:19 UTC, aaronlippold commented on lib/resources/key_rsa.rb
> +    end
http://iasecontent.disa.mil/pki-pke/Certificates_PKCS7_v5.0u1_DoD.zip has examples of valid DoD certs which should give a good idea about the things we would scan for.

2017-03-16 01:26 UTC, aaronlippold requested changes
Overall I think this looks good, I added a couple of comments and a few examples of things that I may be able to make a bit more clear - i.e. what does valid mean? Valid may be a combination of things, signed by and issued by an organization of name x or be signed with a signature that matches a specific email. I added a link to the PKCS#7 dod public certs so you can look at them to see how the three certs are connected to each other - i.e. through issuer and subject - and that may clarify that we want to make 'valid' a different keyword for the core test. The only real question I have is what does 'valid' test?

2017-03-16 01:42 UTC, aaronlippold commented
One part that I would also have is the ability to check a certificates md5,sha-1, and she-256 fingerprints. That would be another way to validate that the cert is the real thing.

2017-03-16 09:17 UTC, chris-rock commented
As discussed with @trickyearlobe I am going to merge his efforts with my efforts

2017-03-21 18:19 UTC, chris-rock commented
I refactored my implementation to use the base implementation from @trickyearlobe

2017-03-21 18:36 UTC, chris-rock commented on lib/resources/key_rsa.rb
> +    end
Would be good to verify what specifically needs to be done to use that.

2017-03-21 18:36 UTC, chris-rock commented on lib/resources/key_rsa.rb
> +    end
Certificates check the following: `certificate? && (now >= not_before && now <= not_after)`

2017-03-21 18:37 UTC, chris-rock commented
cc @DeltaWhy for a review request

2017-03-21 22:11 UTC, adamleff requested changes
This looks really awesome, @chris-rock and @trickyearlobe. I have some comments/questions I've left in my review. I'll be happy to re-review when ready.

2017-03-21 22:11 UTC, adamleff commented on docs/resources/key_rsa.md
> +The `provate_key` property returns the private key or the RSA key pair.
Spelling error: `private_key` instead of `provate_key`

2017-03-21 22:11 UTC, adamleff commented on docs/resources/key_rsa.md
> +The `provate_key` property returns the private key or the RSA key pair.
Also should have an example like the other methods for consistency.

2017-03-21 22:11 UTC, adamleff commented on docs/resources/x509_certificate.md
> +### parsed.XX
Should be `issuer.XX`?

2017-03-21 22:11 UTC, adamleff commented on lib/resources/x509_certificate.rb
> +        its('days_remaining') { should be > 30 }
`validity_in_days`? I don't see a `days_remaining` method.

2017-03-21 22:11 UTC, adamleff commented on docs/resources/x509_certificate.md
> +      its('days_remaining') { should be > 30 }
`validity_in_days`? I don't see a `days_remaining` method.

2017-03-21 22:11 UTC, adamleff commented on docs/resources/x509_certificate.md
> +The `serial` property exposes the serial number of the certificate. The serial number is set by the CA during the signing process and should be unique within that CA.
Let's include an example for consistency with the rest of the documentation.

2017-03-21 22:11 UTC, adamleff commented on docs/resources/x509_certificate.md
> +The `version` property exposes the certificate version.
Let's include an example for consistency with the rest of the documentation.

2017-03-21 22:11 UTC, adamleff commented on docs/resources/x509_certificate.md
> +      its('extensions').length) {should eq 3 }
syntax is wrong here... `its('extensions.length')`?

2017-03-21 22:11 UTC, adamleff commented on docs/resources/x509_certificate.md
> +      its('extensions) { should include 'keyUsage' }
Missing closing `'` on each of the remaining lines in the `its` argument.

2017-03-21 22:11 UTC, adamleff commented on docs/resources/x509_certificate.md
> +      its('extensions['keyUsage']) { should include "Digital Signature" }
Any particular reason you're using hash notation instead of method/dot notation for these examples?

2017-03-21 22:11 UTC, adamleff commented on lib/resources/key_rsa.rb
> +      return skip_resource 'Unable to find private key' unless @key_file.exist?
Since a provided key could be public, should this instead say:

```
"Unable to find key file #{@key_path}"
```

2017-03-21 22:11 UTC, adamleff commented on lib/resources/key_rsa.rb
> +        return skip_resource 'Unable to load private key'
Same comment as above re: public vs. private keys.

2017-03-21 22:11 UTC, adamleff commented on lib/resources/x509_certificate.rb
> +      return if file.nil? || !file.exist? || file.content.nil?
We `skip_resource` in the `key_rsa` resource if the file doesn't exist or is nil. We should probably do the same here, yes?

2017-03-22 08:40 UTC, chris-rock commented on Berksfile
> +cookbook 'openssl', '~> 6'
Switch to openssl cookbook 7.x since https://github.com/chef-cookbooks/openssl/issues/54 is solved now

2017-03-22 08:40 UTC, chris-rock commented on docs/resources/key_rsa.md
> +The `provate_key` property returns the private key or the RSA key pair.
Thank you. I agree.

2017-03-22 08:40 UTC, chris-rock commented on docs/resources/x509_certificate.md
> +      its('days_remaining') { should be > 30 }
Oh yeah, it is `validity_in_days`

2017-03-22 08:40 UTC, chris-rock commented on docs/resources/x509_certificate.md
> +### parsed.XX
correct :-)

2017-03-22 08:40 UTC, chris-rock commented on docs/resources/x509_certificate.md
> +      its('extensions['keyUsage']) { should include "Digital Signature" }
nope, will change it

2017-03-22 08:40 UTC, chris-rock commented on lib/resources/x509_certificate.rb
> +      return if file.nil? || !file.exist? || file.content.nil?
Great idea @adamleff

2017-03-22 09:02 UTC, chris-rock commented
@adamleff I've addressed all your feedback. Let me know if there is anything else I can do.

2017-03-22 11:30 UTC, adamleff approved these changes
This is wonderful! I'm super-excited for these new resources. Excellent work.

2017-03-22 11:30 UTC, merged