Add documentation for passing a Regexp as a Process Name
inspec/inspec pull request #1570
Opened 2017-03-17 14:36 UTC by directionless

2017-03-17 14:37 UTC, directionless commented
I found myself needing to use the source code to figure this out. So, trivial doc patch.

(Yes, I've signed a CLA)

2017-03-22 11:42 UTC, adamleff requested changes
Thanks for your submission, @directionless - just one small tweak for accuracy is needed.

2017-03-22 11:42 UTC, adamleff commented on docs/resources/processes.md.erb
> +* `processes('process_name')` specifies the of a process to check. If this is a string, it will be converted to a Regexp. For more specificity, pass a Regexp directly.
I think this should be `specifies the name of a process to check` - looks like "name" was dropped accidentally.

2017-05-04 08:09 UTC, chris-rock commented
@directionless Thank you for your addition! Once you signed off the commit (https://github.com/chef/inspec/blob/master/CONTRIBUTING.md#dco-sign-off-methods) and changed the text according to @adamleff feedback, we are able to merge this.

2017-05-04 11:51 UTC, adamleff commented
@chris-rock given the age of this PR and that this is a doc-only fix, I'm going to adopt this PR on behalf of the user and get it merged under our obvious-fix / documentation-only fix exception.

2017-05-04 11:52 UTC, chris-rock commented
@adamleff Alright, makes sense.

2017-05-04 12:00 UTC, adamleff commented
Superceded by #1761

2017-05-04 12:00 UTC, closed without merging

2017-05-18 02:20 UTC, directionless commented
Sorry for dropping this! I'm not very good about github notifications.

I think probably would have fallen under the Obvious Fix Policy, but I'm glad @adamleff adopted it. 

Yay