Add an oracle_session resource
inspec/inspec pull request #1751
Opened 2017-05-02 14:50 UTC by nsdavidson

This adds an oracle_session resource similar to the existing resource
for MySQL and MSSQL.  It assumes the sqlplus tool is installed and in
the path of the user InSpec connects as.

Signed-off-by: Nolan Davidson <ndavidson@chef.io>

2017-05-02 16:55 UTC, nsdavidson commented
@arlimus

2017-05-03 10:45 UTC, aaronlippold reviewed
You may want to consider adding:
```def initialize(user = nil, pass = nil, host = localhost, service = nil)``` and `... | sqlplus -s #{@user}/#{@pass}@{@host}/#{@service}")`. This will default the value to localhost but as we found in the postgres resource, it is needed and useful sometime to be able to not force the host value on the backend to just be localhost, especially in the context of a remote test.

2017-05-03 10:48 UTC, aaronlippold reviewed
And also, don't forget to document that you can pass in the host and session values in your examples, but that they default to 'localhost' and to 'nil'.

2017-05-03 11:01 UTC, aaronlippold requested changes
Sorry, forgot to mark this request changes.

2017-05-04 09:24 UTC, chris-rock reviewed
This is a great addition to inspec @nsdavidson
Do you think we can have some kind of integration testing? At least we should add some unit testing similar to https://github.com/chef/inspec/blob/master/test/unit/resources/mysql_conf_test.rb

2017-05-04 09:24 UTC, chris-rock commented on lib/resources/oracle_session.rb
> +      cmd = inspec.command("echo \"#{escaped_query}\" | sqlplus -s #{@user}/#{@pass}@localhost/#{@service}")
we need to be able to parametrize the sqlplus bin. e.g. in a oracle docker container https://store.docker.com/images/oracle-database-enterprise-edition this is located in `/u01/app/oracle/product/12.1.0/dbhome_1/bin/sqlplus`

2017-05-04 09:24 UTC, chris-rock commented on lib/resources/oracle_session.rb
> +    def initialize(user = nil, pass = nil, service = nil)
Do we need to support DB_SID?

2017-05-04 09:24 UTC, chris-rock commented on lib/resources/oracle_session.rb
> +    def initialize(user = nil, pass = nil, service = nil)
Not 100% sure yet, but should we use hash options here like:
```
oracle_session(user: 'my_user', password: 'password')
```

2017-05-04 14:43 UTC, aaronlippold commented on lib/resources/oracle_session.rb
> +    def initialize(user = nil, pass = nil, service = nil)
Yes you need to support DB_SID

I agree, a hash makes sense.

2017-05-04 16:04 UTC, aaronlippold commented on lib/resources/oracle_session.rb
> +      cmd = inspec.command("echo \"#{escaped_query}\" | sqlplus -s #{@user}/#{@pass}@localhost/#{@service}")
If we are going to parametrize, let's parametrize! :) 👍 

```def query(q)
+      escaped_query = q.gsub(/\\/, '\\\\').gsub(/"/, '\\"').gsub(/\$/, '\\$')
+
+      cmd = inspec.command("echo \"#{escaped_query}\" | {@sqlplus_bin} {@sqlplus_opts} #{@user}/#{@pass}@{@host}/#{@service}")
```

2017-05-08 18:24 UTC, nsdavidson commented
Thanks for the feedback @aaronlippold and @chris-rock.  I *believe* I addressed most of your suggestions :).

2017-05-09 11:21 UTC, arlimus approved these changes
This is a great start, thank you @nsdavidson !!

Also kudos to the reviews from @chris-rock and @aaronlippold .

2017-05-09 11:21 UTC, merged