Mysql socket
inspec/inspec pull request #1933
Opened 2017-06-16 14:39 UTC by rshade

2017-06-16 19:04 UTC, adamleff commented
@rshade thanks for your PR!

Unfortunately, we cannot accept this change as written. The `-S/--socket` parameter overrides the `-h/--host` parameter, and we do have users that connect to MySQL instances that are not on the local machine that's being scanned (i.e. testing DB connectivity from a web server, for example).

I verified this by creating a Vagrant machine, installing MySQL, configuring it to listen on 13306 (and forwarded that port), and then tried to connect to it using both `-h` and `-S`:

```
mysql -uvagrant -p -S /tmp/nonexistent.sock -h localhost --port 13306
Enter password:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/nonexistent.sock' (2)
```

One potential solution would be to set the default `socket` parameter to nil, and then have this kind of logic:

```
command = "mysql .... -u username .... "
if !socket.nil?
  command += "-S #{socket}"
else
  command += "-h #{host} ...."
```

That would still allow you to define a socket in your tests without breaking existing users.

2017-06-16 19:04 UTC, adamleff requested changes
Unable to accept as-written, would break existing known use.

2017-06-16 22:14 UTC, adamleff approved these changes
This looks pretty great to me, @rshade, thanks!

If you have time to level-up this change, I would break out the code the builds the CLI command string into a separate method (called `mysql_command` or something similar), and then that will allow us to test that logic easily and independently. If you don't have time for that, lemme know and I can follow-up with another PR to add that as well.

2017-06-17 16:45 UTC, rshade commented
I will try and level up a little beginning of next week. Would it be cool if I open issues on a few of the items and we can work from there?

2017-06-17 16:57 UTC, adamleff commented
That works for me!

2017-06-23 15:28 UTC, chris-rock approved these changes
Thank you @rshade for this improvement

2017-06-23 15:28 UTC, chris-rock commented on lib/resources/mysql_session.rb
> +    def initialize(user = nil, pass = nil, host = 'localhost', port = nil, socket = nil)
In the future we probably want to use opts here to avoid passing nil values

2017-06-23 15:28 UTC, merged

2017-07-18 08:55 UTC, n-rodriguez commented on lib/resources/mysql_session.rb
> +      command += " #{db} -s -S #{@socket} -e \"#{escaped_query}\""
The `-S #{@socket}` argument is redundant with `-h localhost` and leads to MySQL error

2017-07-27 08:10 UTC, stefanandres commented on lib/resources/mysql_session.rb
> +      command += " #{db} -s -S #{@socket} -e \"#{escaped_query}\""
Yep, the current version breaks for all queries without socket connections because of this

2017-07-27 08:15 UTC, stefanandres commented on lib/resources/mysql_session.rb
> +      command += " #{db} -s -S #{@socket} -e \"#{escaped_query}\""
Ah, this is fixed in newer versions.