Website: Disable particle animation if users prefer reduced motion
inspec/inspec pull request #2023
Opened 2017-07-19 20:25 UTC by k-nut

The website uses animations in quite a lot of places. To some people those animations can be a distraction from the text.

Safari introduced the new `prefers-reduced-motion` media query which lets users define that they prefer things not to move so much.

This simple change will check if the users made this setting (in `Accessibility > Display > Reduced Motion`) and if so only show a static version of the particles.

Would you be interested in merging something like this?

More information can be found here: https://webkit.org/blog/7551/responsive-design-for-motion/

![out](https://user-images.githubusercontent.com/1096357/28387657-3f60ceac-6cd0-11e7-8e73-56775b9e846b.gif)

2017-07-20 22:17 UTC, adamleff commented
@k-nut thank you for your PR, and please accept our welcome to the InSpec community!

I think PRs like this are wonderful... enhancing the user experience for EVERYONE is a good thing. I'd like our UX extraordinaire @hannah-radish to chime in on this one since she has more knowledge of the website design than I do.

2017-07-24 05:00 UTC, chris-rock requested changes
Thank you for your improvement @k-nut I added a small request

2017-07-24 05:00 UTC, chris-rock commented on www/source/javascripts/app.js
> +
I would prefer if we could use `window.matchMedia('(prefers-reduced-motion)').matches`

2017-07-24 08:21 UTC, k-nut commented
@chris-rock I added the `window` as proposed (which I agree is a good idea) and pushed a rebased version.

2017-07-26 19:19 UTC, adamleff commented
@k-nut thanks again for this PR! Could you please sign-off on your commit per the [DCO requirements](https://github.com/chef/inspec/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco) so that we can move this forward? thank you!

2017-07-26 20:09 UTC, k-nut commented
@adamleff 📝✅

2017-07-26 20:16 UTC, adamleff approved these changes
Thanks @k-nut!

2017-07-26 20:24 UTC, adamleff commented
I loaded this up in the acceptance environment and it works as described, as well.

2017-07-29 03:30 UTC, chris-rock approved these changes

2017-07-29 04:21 UTC, merged