File Resource: add be_setgid, be_setuid, be_sticky matchers
inspec/inspec pull request #2104
Opened 2017-08-28 17:15 UTC by clintoncwolfe

Fixes #2032.  Supercedes #2095, which was docs-only.

Adds to the File resource (through simple aliasing of existing predicates) be_setgid, be_setuid, and be_sticky.  Adds a provision script to add fixtures; adds simple resource tests; adds first-draft docs for the matchers. 

@kagarmoe had some great doc edits on 101a3cd6 and 07061d0c which are not included here but are obviously welcomed!

2017-08-28 17:18 UTC, adamleff commented
@clintoncwolfe thank you so much for your contribution! I promise to look at this as soon as possible.

2017-08-29 03:09 UTC, adamleff requested changes
@clintoncwolfe this is super, thank you for your first InSpec contribution! I've left a comment re: potentially using the "longer form" matchers of `setgid?` in the docs instead of `sgid?` as I think it's much clearer for the users and eventually I want to deprecate the shorter forms.

With regards to the tests, I honestly don't know if those "resource" tests are used, or how they're expected to be used. I'll need to check with my fellow maintainers. What would be better is if you added these to our `integration` test suite which can be found in `test/integration`

Specifically, you'd want to add any additional test prep to the [Chef cookbook here](https://github.com/chef/inspec/blob/master/test/cookbooks/os_prepare/recipes/file.rb) and then put your tests [here](https://github.com/chef/inspec/blob/master/test/integration/default/controls/file_spec.rb). You should then be able to fire up any of the Test Kitchen "default" suite instances for an OS of your choice to validate those tests. These are the tests that fire during the Travis runs.

Would you mind moving your tests over to integration?

2017-08-29 03:09 UTC, adamleff commented on docs/resources/file.md.erb
> +    it { should be_sgid }
Since we kinda want to get rid of the `sgid?` method and go with the clearer `setgid?`, should we advertise the clearer matcher instead?

2017-08-29 03:09 UTC, adamleff commented on docs/resources/file.md.erb
> +    it { should be_suid }
Same as above... `setuid` instead of `suid`? What do you think?

2017-08-29 15:14 UTC, clintoncwolfe commented
Sorry about that docs issue - suid/setuid, etc should have been updated, and I just cherry picked the old commit.  Straightforward.

I'll move the tests, that will take a bit longer.

2017-08-30 18:04 UTC, adamleff commented
@clintoncwolfe no problem re: the tests. If you find yourself not being able to free up some time to work on them, I can likely help contribute as well. Just let me know. Thanks again!

2017-09-01 19:04 UTC, clintoncwolfe commented
@adamleff Turns out the test fixture was already [in place](https://github.com/chef/inspec/blob/master/test/cookbooks/os_prepare/recipes/file.rb#L28), so this was a simple matter of adding the tests.  I wasn't able to run the integration suites myself on vagrant-VirtualBox or AWS; they need some updating - see [slack conversation](https://chefcommunity.slack.com/archives/C1XB6U6MN/p1504290250000092)

2017-09-01 19:22 UTC, adamleff commented
Thanks @clintoncwolfe! can we remove the changes to the following files since we decided to keep the tests in the `integration` section?

 * `test/test.yaml`
 * `test/setgid-setuid-sticky.sh` (delete file)
 * `test/resource/file_test.rb`

If the other maintainers enlighten me as to why we need to keep the `test/resource` stuff alive, I'll take responsibility for adding these back in.

Thanks!

2017-09-01 21:21 UTC, adamleff approved these changes
Superb change, @clintoncwolfe! Thanks again!

2017-09-03 18:43 UTC, arlimus approved these changes
Sweet addition, thank you @clintoncwolfe !! 😁

2017-09-03 18:43 UTC, merged