Support profile versions for automate profiles storage
inspec/inspec pull request #2128
Opened 2017-09-08 14:15 UTC by alexpop

After `inspec compliance login_automate ...`

```
$ be inspec compliance exec compliance://admin/apache-baseline#2.0.1

Profile: DevSec Apache Baseline (apache-baseline)
Version: 2.0.1
...
```

```
$ be inspec compliance exec admin/apache-baseline

Profile: DevSec Apache Baseline (apache-baseline)
Version: 2.0.2
```

```
$ be inspec exec compliance://admin/apache-baseline#2.0.1

Profile: DevSec Apache Baseline (apache-baseline)
Version: 2.0.1
```

```
$ be inspec exec compliance://admin/apache-baseline

Profile: DevSec Apache Baseline (apache-baseline)
Version: 2.0.2
```

```
$ be inspec compliance download compliance://admin/apache-baseline#2.0.1
Downloading `admin/apache-baseline#2.0.1`
Profile stored to apache-baseline#2.0.1.tar.gz
$ inspec json apache-baseline#2.0.1.tar.gz | jq .version
"2.0.1"
```

2017-09-08 14:23 UTC, adamleff requested changes
Change looks fine overall. Can we please add some unit tests for `.target_url` and `.profile_split`? I'd like to see both tests for profile names that include and don't include a version string to prevent future regressions.

2017-09-08 14:23 UTC, adamleff commented on lib/bundles/inspec-compliance/api.rb
> +        index = profiles.index { |p|
Multiline blocks should use `do..end` please :)

2017-09-08 14:23 UTC, adamleff commented on lib/bundles/inspec-compliance/api.rb
> +        index = profiles.index { |p|
We never really use the index except for checking to see if we have a match. Could we refactor this to use `#any?` instead while we're in here?

```ruby
profiles.any? do |p|
  # criteria
end
```

... that should return true if there was a match, false if not.

2017-09-08 14:29 UTC, adamleff commented
We also need to update the inspec-compliance README since this is a new enhancement.

2017-09-08 18:40 UTC, alexpop commented
Makes sense Adam, appreciate the review. Will return next week and finish this up.

2017-09-13 16:11 UTC, alexpop commented
Adam, I added a second commit to the PR that:
* addresses the code refactor you mentioned
* updates the inspec-compliance bundle README
* adds tests (Wasn't able to stub the `profiles` method in the `exist?` test. Can you have a look at that please?)

Cheers!

2017-09-13 17:03 UTC, adamleff commented
@alexpop I think I squared away the pending errors and did a little refactor of one method. Please check 33f57aa0 and see if that meets your needs. The tests should go green shortly.

2017-09-13 17:34 UTC, adamleff approved these changes
Looks good with my clean-up commit. @alexpop please confirm!

2017-09-13 20:51 UTC, alexpop commented
Looks very good Adam, happy to merge!

2017-09-13 20:53 UTC, merged