Add hotfix resource for Windows
inspec/inspec pull request #2178
Opened 2017-09-22 12:35 UTC by mattray

Adds the ability to check if WIndows hotfixes of the form "KB1234567" are installed or not.

Signed-off-by: Matt Ray <matthewhray@gmail.com>

2017-09-22 12:39 UTC, mattray commented
I wasn't sure how to provide an integration test, KBs are specific to different versions of Windows and many get rolled-up into larger service packs. I do have a working integration test for Windows 2012r2.
```ruby
describe hotfix('KB4019215') do
  it { should be_installed }
end

describe hotfix('KB9999999') do
  it { should_not be_installed }
end
```
```shell
$ bundle exec bin/inspec exec . -t winrm://vagrant@127.0.0.1 --password "vagrant" -p 55985

Profile: tests from .
Version: (not specified)
Target:  winrm://vagrant@http://127.0.0.1:55985/wsman:3389

  Hotfix KB4019215
     ✔  should be installed
  Hotfix KB9999999
     ✔  should not be installed

Test Summary: 2 successful, 0 failures, 0 skipped
```

2017-09-22 12:55 UTC, adamleff requested changes
Hi @mattray! Thanks for this, this is a great addition.

Any chance I can convince you to name the resource `windows_hotfix` instead so we don't have to worry about resource name confusion if we ever have a hotfix-like resource for something else?

Re: integration test, one way of doing this might be to have the chef recipe that sets up the test node query for any installed hotfixes and write out an installed hotfix ID to the filesystem, and then the integration test could read from that file. That way we don't have to worry about catering to different OS flavors and potential roll-ups eating individual IDs.

2017-09-22 12:55 UTC, adamleff commented on test/unit/resources/hotfix_test.rb
> +  end
Can we add a test for a hotfix that doesn't exist, along with the mock command output we should expect?

2017-09-22 21:31 UTC, mattray commented
@adamleff I upgraded the PR with your feedback on the windows_hotfix name and added the other test. It will take awhile to sort the integration test, since it's my weekend here in 🇦🇺

2017-09-22 21:41 UTC, adamleff commented
Thanks @mattray! The changes look good though you've got some failing Rubocop tests (sorry).

Let me know next week about the integration test progress. If it's going to be a while, we can merge this in and follow-up on the integration tests later.

2017-09-22 21:55 UTC, mattray commented
Undid the change that made Rubocop unhappy.

2017-09-24 00:38 UTC, mattray commented
I'm working on an integration test based on querying the existing KBs applied and then checking with the ```windows_hotfix``` resource. If you merge this I'll have it ready in the next day or two in a separate PR so I don't have to keep rebasing this one.

2017-09-25 08:37 UTC, mattray commented
I've added an integration test that works against my vagrant-based Windows 2012r2.

2017-09-25 16:16 UTC, adamleff approved these changes
This looks great, @mattray. Thank you!

2017-09-25 17:09 UTC, arlimus approved these changes
This is a great addition, thank you @mattray !!

2017-09-25 17:09 UTC, merged