allow users to configure the profiles namespace
inspec/inspec pull request #2275
Opened 2017-10-30 18:32 UTC by arlimus

By default it uses the username of the user that is logged into the system. However, the user can now specify the `--user` on the cli to list profiles from a user other than his own domain.

2017-10-30 18:44 UTC, chris-rock approved these changes
This works like a charm. Thank you @arlimus

2017-10-30 18:57 UTC, adamleff approved these changes
Looks good! Holding off on merging per a quick chat with @chris-rock and awaiting Travis to go green (they're having issues currently).

2017-10-31 10:25 UTC, chris-rock commented
I updated the PR to cover a little bit more. It supports the following now:

* list and upload a profile to another owner:
<img width="925" alt="screen shot 2017-10-31 at 11 13 04 am" src="https://user-images.githubusercontent.com/1178413/32219238-cc05b486-be2d-11e7-9076-9e03ec4bdfff.png">

* profile inheritance with an alternative namespace

Just define the right namespace in `inspec.yml`:
```
depends:
  - name: profile
    compliance: drichter/profile
```
The following shows the result before this branch and after this branch
<img width="644" alt="screen shot 2017-10-31 at 11 19 54 am" src="https://user-images.githubusercontent.com/1178413/32219274-ea684902-be2d-11e7-984b-963e5862290b.png">

2017-10-31 10:27 UTC, chris-rock commented
fixes #1500

2017-10-31 19:17 UTC, adamleff requested changes

2017-10-31 19:17 UTC, adamleff commented on lib/bundles/inspec-compliance/api.rb
> +      c = config.dup
The `c` variable looks unused. Why is it needed? Looks like we can just delete lines 93 and 94, yes?

2017-10-31 19:17 UTC, adamleff commented on lib/bundles/inspec-compliance/cli.rb
> +      c = config.dup
What was your thinking for needing to `dup` this here vs. just using the existing `config`? We don't return it to the caller, and everything else we pass `config` to appears to potentially need the `owner` and the rest of the `config` object anyways. It just seems unclear to me.

We should also be more explicit with our variable names. `c` isn't very descriptive but it's used throughout this method now.

2017-11-07 19:01 UTC, adamleff approved these changes
Thanks for your collective work on this, @arlimus and @chris-rock!

2017-11-07 19:01 UTC, merged