http resource: supply max-time option using read_timeout and open_timeout
inspec/inspec pull request #2289
Opened 2017-11-06 12:24 UTC by bdellegrazie

Curl doesn't distinguish between them so need to use the sum of both as
the overall timeout.

fixes #2288

2017-11-07 22:31 UTC, adamleff requested changes
@bdellegrazie thanks for your first PR to InSpec! Great contribution!

Unfortunately, you have some test failures. The curl commands get mocked by our MockLoader so we can test the resource end-to-end, and they use exact matches against the command. Because your PR changed the command, the mocks are no longer valid. You can find the mocks configured here:

https://github.com/chef/inspec/blob/master/test/helper.rb#L455-L466

Essentially, you need to add your new flag so the commands are properly mocked and then you should be fine.

You can run the tests manually on your workstation like so:

 - bundle install
 - bundle exec m test/unit/resources/http_test.rb

If you run the above BEFORE you fix the mocks, you should see errors indicating "command not mocked" that will give you more clues.

2017-11-07 23:10 UTC, bdellegrazie commented
@adamleff certainly, will do.

2017-11-07 23:30 UTC, bdellegrazie commented
@adamleff updated, please re-review at your earliest convenience, thanks!

2017-11-08 17:43 UTC, adamleff approved these changes
Super job, @bdellegrazie - thanks for your contribution!

2017-11-09 10:11 UTC, chris-rock approved these changes
Great work @bdellegrazie Thank you very much.

2017-11-09 10:11 UTC, merged