DO NOT MERGE - Testing breaking Train name change
inspec/inspec pull request #2397
Opened 2017-12-14 18:10 UTC by jquick

🚫 DO NOT MERGE 💀 

Signed-off-by: Jared Quick <jquick@chef.io>

2017-12-20 16:45 UTC, jquick commented
@adamleff - I think this is ready for review, it will want to go in tandem with the train release. https://github.com/chef/train/pull/228

2017-12-20 23:17 UTC, adamleff requested changes
Can we add a couple of unit tests for `NameCleaned`? I'm thinking something for when translation was necessary, and something for when it wasn't? Just some checks using the `==` method you define should be good.

2017-12-20 23:17 UTC, adamleff commented on lib/resources/os.rb
> +        super(other)
We want to compare against `cleaned` if we had to translate, right?

2017-12-20 23:17 UTC, adamleff commented on lib/resources/os.rb
> +      return self.name if name == :name
For clarity purposes, we should probably change the method parameter from `name` to `key` or something like that so we're not overloading the use of `name` here.

2017-12-21 22:17 UTC, adamleff requested changes

2017-12-21 22:17 UTC, adamleff commented on test/unit/resources/os_test.rb
> +  it 'verify NamedCleaned with uppercase' do
Forgive the pun, but can we `Clean` this up a bit?

```ruby
let(:cleaner) { Inspec::Resources::OSResource::NameCleaned }

it 'does something' do
  cleaner.new('blah')
  # some test here
end
```

It feels repetitious to be defining `cleaner` in each test like that. If you don't want to use a `let`, we should at least consolidate two lines per test:

```ruby
it 'does something' do
  name = Inspec::Resources::OSResource::NameCleaned.new('something')
  # the test
end
```

2018-01-02 01:44 UTC, adamleff approved these changes
Conditionally approved pending a train release and a commit here that uses it.

2018-01-04 19:14 UTC, adamleff approved these changes

2018-01-04 19:15 UTC, merged