Update security_policy resource to return Names, not SIDs
inspec/inspec pull request #2462
Opened 2018-01-16 14:29 UTC by ViolentOr

Added possibility to translate SID to human-readable name. As it would be a breaking change, i added optional 'translate_sid' param to the resource.

Calling the resource 
```ruby
security_policy
```
would return previous output.

Calling it 
```ruby
security_policy(translate_sid: true)
```
will attempt to translate sid to human-readable name.

For example
```ruby
describe security_policy(translate_sid: true) do       
  its('SeNetworkLogonRight') { should include "NT AUTHORITY\\Authenticated Users" }
end
```
will return

>  Security Policy
>      [PASS]  SeNetworkLogonRight should include "NT AUTHORITY\\Authenticated Users"

2018-01-19 22:11 UTC, adamleff requested changes
Hi, @ViolentOr! Thank you for your contribution!

I have some suggestions for you on some better naming of variables. Also, before we can accept this, we need to add some unit tests to cover this new behavior. The two tests I can think of right away are:

 - set translate_sid to true and expect InSpec to successfully translate
 - set translate_sid to true, expect InSpec to fail to translate, and ensure the SID is returned instead of the failed translated name

Please let us know if you need guidance on how to proceed with adding those unit tests. Again, thanks for your contribution!

2018-01-19 22:11 UTC, adamleff commented on lib/resources/security_policy.rb
> +    def initialize(pars = {})
To be consistent with other resources, can you change this from `pars` to `opts`?

2018-01-19 22:11 UTC, adamleff commented on lib/resources/security_policy.rb
> +            temp = inspec.command("(New-Object System.Security.Principal.SecurityIdentifier(\"#{v.sub('*S', 'S')}\")).Translate( [System.Security.Principal.NTAccount]).Value").stdout.to_s.strip
A better variable name here would be `policy_name` or something similar to that, rather than `temp`

2018-01-21 15:38 UTC, ViolentOr commented
@adamleff thank you for suggestions. Some of them are addressed.
As for

> Also, before we can accept this, we need to add some unit tests to cover this new behavior.

I'll do my best. But i don't have ruby-development environment, it would be kind of walking in the dark. Tests are not hard though, i think i'll manage =)

2018-01-21 19:20 UTC, ViolentOr commented
@adamleff take a look now, please.

I'm not sure, what is wrong with the TravisCI test... but it doesn't look like this PR is the reason of it =)

2018-01-23 18:09 UTC, adamleff approved these changes
Looks good to me, thanks @ViolentOr!

2018-01-23 20:31 UTC, arlimus approved these changes
I love the addition of translated SIDs, thank you for contributing this @ViolentOr !!

2018-01-23 20:31 UTC, merged