Improve links to Learn Chef Rally
inspec/inspec pull request #2476
Opened 2018-01-23 03:55 UTC by tpetchel

We recently published some updates to Learn Chef Rally that we'd like to highlight.

2018-01-23 13:40 UTC, chris-rock approved these changes
Thank you @tpetchel for that improvement

2018-01-23 18:27 UTC, adamleff requested changes
Changes overall look good. One wording modification I'd like to see for clarity before merge/release.

2018-01-23 18:27 UTC, adamleff commented on www/source/tutorials.html.slim
>      p.clear Huge thanks to Annie Hedgpeth for creating all of these fantastic tutorials.
To make it clear which of the tutorials are Annie's, I suggest changing this line to:

"Huge thanks to Annie Hedgpeth for creating all of the following fantastic tutorials:"

2018-01-31 10:50 UTC, chris-rock commented
@tpetchel Anything we can help to get this in?

2018-01-31 12:01 UTC, adamleff commented
This is a good change as-is so I'll merge it and then put forth a quick one-liner change to update.

2018-01-31 12:01 UTC, merged