Add additional links to Learn Chef Rally content
inspec/inspec pull request #2477
Opened 2018-01-23 14:51 UTC by tpetchel

This change adds links to specific Learn Chef content to help users learn about certain topics.

I also fixed the "under construction" page. It was not rendering correctly.
I also corrected a few caplitalization issues and edited a few sentences for clarity.

2018-01-31 10:53 UTC, chris-rock requested changes
Great improvement @tpetchel I found a small thing we need to update

2018-01-31 10:53 UTC, chris-rock commented on www/source/under_construction.html.slim
> +          a.button href="http://slack.habitat.sh" target="_blank" Reach out on Slack
While we are at it, we need to use `http://community-slack.chef.io/` here

2018-02-21 04:50 UTC, tpetchel commented
@chris-rock - sorry I missed your suggestion. Great catch! I patched that up and merged against the latest `master`.

2018-02-27 02:43 UTC, miah approved these changes
This looks good. I think after the conflict is fixed we can merge.

2018-02-27 14:58 UTC, jquick commented
Hey @tpetchel - Do you mind rebasing this vs master? We had a few doc changes that went in.

2018-03-13 20:41 UTC, jquick approved these changes
Thanks @tpetchel !

2018-03-14 15:00 UTC, chris-rock approved these changes
Thank you @tpetchel

2018-03-14 15:01 UTC, merged