Add caution to "mode": include leading zero in file mode specifications
inspec/inspec pull request #2606
Opened 2018-02-11 03:32 UTC by atsaloli

2018-02-11 15:12 UTC, aaronlippold requested changes
Great first start. We need to make a few updates and don't forget to sign your commit or we will be blocked getting it through.

You should use active language, something like:

The `mode` property uses the OCTAL format to compare modes, so you must write your numeric mode specification starting with zero. See: https://en.wikipedia.org/wiki/Leading_zero#0_as_a_prefix.

For example, the mode specification of `644`, ("-rw-r--r--" ) should be written as:

`{ should cmp '0644' }`, as shown above.

If not, it will be taken as a the decimal '1024' in octal by Ruby, and your test will fail.

( Note to implementer:

Does it makes sense to also have this section?? We may also want to 'link' to the `is_sticky`, `is_guid` and `is_suid` properties here as well as it connects logically using a style like below )

If you want to validate the `sticky bit` or the `suid/guid` bits, you can add the needed octet as:
`{ should cmp '00644' }`
... ( suid example )
... ( guid example )

For the best readability, use the provided `matchers` - <link to sticky>,<be_suid> and <be_guid>

`{ should be_sticky }` 
and
`{ should be_suid }`
`{ should be_guid }`

2018-02-15 18:20 UTC, atsaloli commented
Thanks @aaronlippold !  Who is the "implementer" you addressed?

2018-03-01 14:28 UTC, jquick reviewed
Thanks @atsaloli ! This is a great addition. Some small personal suggestions.

2018-03-01 14:29 UTC, jquick commented on docs/resources/file.md.erb
> +You must write the numeric mode specification starting with zero, to tell Ruby
Would you mind changing `Ruby` to `InSpec`? We have a lot of non-tech people using these docs and it may be more clear.

2018-03-01 14:29 UTC, jquick commented on docs/resources/file.md.erb
> +then Ruby will understand it as _decimal_ 644, which is octal 1024 or
Same as above.

2018-03-01 15:23 UTC, atsaloli commented
Great! I appreciate your attention to usability, @jquick 

I forgot to add the 

    Signed-off-by: Aleksey Tsalolikhin <aleksey@verticalsysadmin.com>

to the last commit, and I'm not sure how to fix that at this point.   There is no IP in it anyway.

2018-03-01 16:35 UTC, jquick commented
Hey @atsaloli you should be able to do:
```
git commit --amend -s
then save/write
git push -f
```
To sign it off.

2018-03-01 19:38 UTC, kagarmoe requested changes

2018-03-01 19:38 UTC, kagarmoe commented on docs/resources/file.md.erb
> +the value is [octal](https://en.wikipedia.org/wiki/Leading_zero#0_as_a_prefix).
InSpec [octal](https://en.wikipedia.org/wiki/Leading_zero#0_as_a_prefix) values begin the numeric mode specification with zero.

2018-03-01 19:38 UTC, kagarmoe commented on docs/resources/file.md.erb
> +If you write it as
Without the zero prefix for the octal value, the InSpec will interpret the it as the _decimal_ value 644, which is octal 1024 or`-----w-r-T`, and any test for a file that is `-rw-r--r--` will fail.

2018-03-02 01:23 UTC, atsaloli commented
@jquick : how do I find out the URL of my atsaloli:patch-1 so I can "git clone" it and add the sign-off to every commit, please?

@kagarmoe: your wording is much better, I like how direct and simple it is.

2018-03-02 05:15 UTC, aaronlippold commented
The implementer is you, @jquick and @kagarmoe ... i.e. asking - do you guys think we should also address these realted issues here - guid, suid and stickly bit.

2018-03-02 13:59 UTC, jquick commented
@aaronlippold - I think that would be a great follow up pr from someone. For now I think the scope of this ticket is complete. Thanks for your work on this @atsaloli !

2018-03-02 13:59 UTC, jquick approved these changes

2018-03-02 18:42 UTC, kagarmoe approved these changes

2018-03-02 18:47 UTC, merged

2018-03-03 23:17 UTC, atsaloli commented
Thank you all!!  :)