Kg/k module
inspec/inspec pull request #2626
Opened 2018-02-13 00:29 UTC by kagarmoe

2018-02-13 14:11 UTC, jquick commented on docs/resources/kernel_module.md.erb
> +    its(:version) { should eq '3.2.2' }
Do we have other resources with symbol properties? I confirmed 'version' works as well.

2018-02-27 00:09 UTC, jerryaldrichiii requested changes
Looks great @kagarmoe just a few suggestions/questions.

2018-02-27 00:09 UTC, jerryaldrichiii commented on docs/resources/kernel_module.md.erb
> +=======
Is this line needed? Could we remove it?

2018-02-27 00:09 UTC, jerryaldrichiii commented on docs/resources/kernel_module.md.erb
>  ### Test a modules 'version'
Not part of your change but could we change this to `module's`

2018-02-27 00:09 UTC, jerryaldrichiii commented on docs/resources/kernel_module.md.erb
> +The `version` property tests if the named module version is on the system:
I would reword this to something like:

```
The `version` property tests if the named module on the system has the correct version:
```

2018-02-27 18:31 UTC, jerryaldrichiii requested changes
Great job! Only one suggestion.

2018-02-27 18:31 UTC, jerryaldrichiii commented on docs/resources/kernel_module.md.erb
> +The `be_loaded` matcher tests if the module is a loadable kernel module:
Could we change this to:

```
The `be_loaded` matcher tests if the named module is loaded:
```

2018-02-28 20:37 UTC, jerryaldrichiii approved these changes
Looks great @kagarmoe thank you for all the iterations.

2018-02-28 22:12 UTC, jquick approved these changes
Thanks @kagarmoe !

2018-02-28 22:12 UTC, merged