New Resource aws_config_recorder
inspec/inspec pull request #2635
Opened 2018-02-14 01:34 UTC by dromazmj

* Adds functionality to be able to test an AWS Configuration Recorder

2018-02-26 14:45 UTC, clintoncwolfe requested changes
Very good! A few matchers to rename and doc edits, and some changes in exception handling.   Your tests are very thorough - great work, this will be very useful!

2018-02-26 14:45 UTC, clintoncwolfe commented on docs/resources/aws_config_recorder.md
> +---
Docs files should now end in .md.erb

2018-02-26 14:45 UTC, clintoncwolfe commented on docs/resources/aws_config_recorder.md
> +# aws_config_recorder
Escape underscores in unquoted doc strings

2018-02-26 14:45 UTC, clintoncwolfe commented on docs/resources/aws_config_recorder.md
> +Use the `aws_config_recorder` InSpec audit resource to test properties of your aws config service.
Capitalize: "AWS Config service".  That helps make it clear we're talking about a specific offering from AWS.

2018-02-26 14:45 UTC, clintoncwolfe commented on docs/resources/aws_config_recorder.md
> +Use the `aws_config_recorder` InSpec audit resource to test properties of your aws config service.
Might also be good to describe what a Config Recorder is.  What does it represent in the Config Service?  What does it interact with?

2018-02-26 14:45 UTC, clintoncwolfe commented on docs/resources/aws_config_recorder.md
> +Provides the IAM role arn associated with the configuration recorder.
A few words about what the role is used for might be good.

2018-02-26 14:45 UTC, clintoncwolfe commented on docs/resources/aws_config_recorder.md
> +      its('resource_types') { should eq ['AWS::EC2::CustomerGateway', 'AWS::EC2::EIP'] }
Array equality is problematic - there are sorting issues, for example (see #2739 for some discussion on that).  In examples, I recommend using the `include` matcher and splitting the tests:

```
its('resource_types') { should include 'AWS::EC2::CustomerGateway' }
its('resource_types') { should include 'AWS::EC2::EIP' }
```

2018-02-26 14:45 UTC, clintoncwolfe commented on docs/resources/aws_config_recorder.md
> +Provides whether AWS Config records configuration is changed for each type of regional resource.
Ok, we need to rename this one for fluency, and also smooth out that description.  How about:

```
be_recording_all_resource_types
record_all_resource_types  # This would require a matcher_alias call
```
And for the prose:
"Indicates if the ConfigurationRecorder will record changes for all resources, regardless of type.  If this is true, resource_types is ignored."

2018-02-26 14:45 UTC, clintoncwolfe commented on docs/resources/aws_config_recorder.md
> +Provides a list of AWS resource types for which the AWS Config records configuration will change.
Might also add "Note that if `be_recording_all_resource_types` is true, this property is meaningless and may be an empty list."

2018-02-26 14:45 UTC, clintoncwolfe commented on docs/resources/aws_config_recorder.md
> +Provides whether or not the AWS Config includes support for all global resource types.
"Indicates whether the ConfigurationRecorder will record changes for global resource types (such as IAM Users)."

I think we should rename this:
```
be_recording_all_global_types
record_all_global_types  # This would require a matcher_alias call
```
Better ideas welcome!

2018-02-26 14:45 UTC, clintoncwolfe commented on lib/resources/aws/aws_config_recorder.rb
> +    @resp = backend.describe_configuration_recorder_status(@query)
Wrap in catch_aws_errors

2018-02-26 14:45 UTC, clintoncwolfe commented on lib/resources/aws/aws_config_recorder.rb
> +    @status = @resp.configuration_recorders_status.first.to_h
I'm always leery at accepting the first result from a possibly unsorted array.  How do we know it's the right one?

2018-02-26 14:45 UTC, clintoncwolfe commented on lib/resources/aws/aws_config_recorder.rb
> +    @resp = backend.describe_configuration_recorders(@query)
wrap in catch_aws_errors

2018-02-26 14:45 UTC, clintoncwolfe commented on lib/resources/aws/aws_config_recorder.rb
> +      rescue Aws::ConfigService::Errors::NoSuchConfigurationRecorderException
Don't catch exceptions here - catch them in fetch_from_api.  It's part of the contract of the AWS API that it will throw that exception.  If you catch it here, that means we're not testing for exception handling elsewhere.

2018-02-26 14:45 UTC, clintoncwolfe commented on test/aws/default/verify/controls/aws_config_recorder.rb
> +    description: 'See ../build/iam.tf',
copypasta - config.tf

2018-02-26 14:45 UTC, clintoncwolfe commented on test/unit/resources/aws_config_recorder_test.rb
> +      recorders['empty']
You should raise `Aws::ConfigService::Errors::NoSuchConfigurationRecorderException` here

2018-02-26 22:55 UTC, dromazmj commented on lib/resources/aws/aws_config_recorder.rb
> +    @status = @resp.configuration_recorders_status.first.to_h
The first one will always work because you are specifying the recording name.  So then it will always return an array of one element

2018-02-27 17:08 UTC, clintoncwolfe approved these changes

2018-02-27 17:58 UTC, jquick approved these changes
This looks good to me! Thanks @dromazmj !

2018-02-27 18:15 UTC, merged