aws_cloudtrail_trail feature: test how many days ago logs were delivered
inspec/inspec pull request #2887
Opened 2018-03-27 20:24 UTC by dromazmj

* Adds new property to test how many days ago the CloudTrail delivered logs to the CloudWatch Logs.
* This feature is needed in order to complete the cis aws benchmark

Signed-off-by: Matthew Dromazos <dromazmj@dukes.jmu.edu>

2018-03-29 15:52 UTC, pwelch requested changes
@dromazmj Thanks for adding this! Just a couple small suggestions.

2018-03-29 15:52 UTC, pwelch commented on test/unit/resources/aws_cloudtrail_trail_test.rb
> +          latest_cloud_watch_logs_delivery_time: TIME_NOW
@dromazmj Since this is only used in one place right now, could we change `TIME_NOW` to `Time.now`?

2018-03-29 15:52 UTC, pwelch commented on test/unit/resources/aws_cloudtrail_trail_test.rb
> +      selected
Could we skip the assignment and return the result of the fixture value? 
```ruby
fixtures.detect { |f| f.name == query[:name] }
```

2018-04-03 13:55 UTC, pwelch approved these changes
Thanks @dromazmj !

2018-04-06 18:04 UTC, jquick approved these changes
Thanks @dromazmj !

2018-04-06 18:04 UTC, merged