Add aws_elb and aws_elbs resources
inspec/inspec pull request #3079
Opened 2018-05-26 00:47 UTC by clintoncwolfe

Adds `aws_elb` singular and `aws_elbs` plural resources.  Fairly straightforward if long-winded.

One change of note: I adjusted the way CIDRs are calculated for subnets in the Terraform code, to be more flexible.

2018-06-01 17:25 UTC, jquick approved these changes
Nice additions @clintoncwolfe !

2018-06-06 21:11 UTC, jerryaldrichiii requested changes
Looks good to me! Just a few minor things.

2018-06-06 21:11 UTC, jerryaldrichiii commented on docs/resources/aws_elbs.md.erb
> +The name of the ELB within AWS. The ELB name is unique within the region. If you know the full ELB name, you should use the `aws_elb` resource instead, as it is much more efficient.
Could we change this to say `much more efficient for testing a specific ELB`?

2018-06-06 21:11 UTC, jerryaldrichiii commented on test/integration/aws/default/build/ec2.tf
> +# This is the
It is the? :smile:

2018-06-07 17:55 UTC, clintoncwolfe commented on test/integration/aws/default/build/ec2.tf
> +# This is the
Deleted - I have no idea what that was!

2018-06-07 18:07 UTC, jerryaldrichiii approved these changes
Looks great! Thanks @clintoncwolfe.

2018-06-07 19:06 UTC, merged