Update core resources with filtertable API changes
inspec/inspec pull request #3117
Opened 2018-06-06 21:03 UTC by clintoncwolfe

This updates all core resources to:
 * rename `add` to one of the three aliases, as appropriate (`register_column`, `register_custom_matcher`, `register_custom_property`)
 * remove all but one call to `add_accessor` (these are now provided automatically)
 * rename `connect` to `install_filter_methods_on_resource`
 * remove any matcher named `exists?` (`exist?` is the standard term, and RSpec was making it accidentally work - see [here](
https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/exist-matcher)

There are a lot of lines changed, but they are all simple.  Main motivation for this is so that future code browsers / copiers will get on the right foot.

2018-06-07 17:28 UTC, clintoncwolfe commented
Temporarily withdrawing this - I'm going to separate out the deletion of the `exists?` matcher onto a separate PR.

2018-06-07 18:42 UTC, clintoncwolfe commented
Reverted removal of `exists?`, re-opening

2018-06-26 15:14 UTC, jerryaldrichiii requested changes
Looks great, only feedback is style related.

Not sure what the proper term is, but on lining up the `field`s, should it be two spaces after the longest item? Seems there is some extra space in a few of these. It also seems like some are not aligned.

Let me know if this is not really an issue.

2018-06-26 15:46 UTC, clintoncwolfe commented
Well, rubocop passes, which has always been by gatekeeper of style.  Do you feel we should update the rubocop rules?

2018-06-26 16:59 UTC, miah approved these changes
Thank you for taking the time to clean up existing code after changing filtertable =)

2018-06-26 17:50 UTC, jquick approved these changes
Very nice cleanup! Thanks @clintoncwolfe

2018-06-26 17:51 UTC, jerryaldrichiii commented
I think rubocop is a good start but cannot be the only gatekeeper

...but since I have no argument save for subjective ones:

![ill-allow-it.gif](https://media.giphy.com/media/jchcqpyTpIki4/source.gif)

2018-06-26 17:51 UTC, jerryaldrichiii approved these changes

2018-06-26 19:14 UTC, merged