Refactor 'inspec init profile' into a reusable component.
inspec/inspec pull request #3202
Opened 2018-07-09 17:51 UTC by mattray

base_cli.rb had several methods used internally, these are exposed so
lib/bundles/inspec-init/profile.rb can act as a library for anything
that needs to create new Inspec profiles programatically (ie. inspec-iggy)

Additional PRs will add CLI options similar to "chef generate cookbook"

Signed-off-by: Matt Ray <matthewhray@gmail.com>

2018-07-09 18:48 UTC, clintoncwolfe requested changes
This is a great idea.  Some coding issues we need to address, though.  First, we need the rubocop issues fixed; then the change in scope of the formatters needs to be reverted, or many functional tests will break.  I may adopt this if needed.

2018-07-09 18:48 UTC, clintoncwolfe commented on lib/bundles/inspec-init/profile.rb
> +  class Profile
I'd suggest the name `ProfileGenerator`, as it is more in line with the meaning.  Or `ProfileTemplater`.

2018-07-09 18:48 UTC, clintoncwolfe commented on lib/bundles/inspec-init/cli.rb
> +        Init::Profile.generator(relative.to_s, { name: name }, options)
I'm not sure this make sense to become a class method

2018-07-09 18:48 UTC, clintoncwolfe commented on lib/inspec/base_cli.rb
> +    def self.mark_text(text)
OK, I think what you want is "I want my base CLI class to help me with formatting".  Make these public, instance methods, not "attempted private" class methods. 

Then, have ProfileGenerator inherit from here, or we make a real UI object.

2018-07-10 12:25 UTC, aaronlippold commented
I think this will be a very valuable addition small though it is:-)

On Mon, Jul 9, 2018, 2:48 PM Clinton Wolfe <notifications@github.com> wrote:

> *@clintoncwolfe* requested changes on this pull request.
>
> First, we need the rubocop issues fixed; then the change in scope of the
> formatters needs to be reverted, or many functional tests will break. I may
> adopt this if needed.
> ------------------------------
>
> In lib/bundles/inspec-init/profile.rb
> <https://github.com/inspec/inspec/pull/3202#discussion_r201099654>:
>
> > @@ -0,0 +1,69 @@
> +module Init
> +  class Profile
>
> I'd suggest the name ProfileGenerator, as it is more in line with the
> meaning. Or ProfileTemplater.
> ------------------------------
>
> In lib/bundles/inspec-init/cli.rb
> <https://github.com/inspec/inspec/pull/3202#discussion_r201100739>:
>
> >        define_method relative.to_s.to_sym do |name|
> -        generator(relative.to_s, { name: name }, options)
> +        Init::Profile.generator(relative.to_s, { name: name }, options)
>
> I'm not sure this make sense to become a class method
> ------------------------------
>
> In lib/inspec/base_cli.rb
> <https://github.com/inspec/inspec/pull/3202#discussion_r201108854>:
>
> > @@ -364,15 +364,15 @@ def configure_logger(o)
>        o[:logger].level = get_log_level(o.log_level)
>      end
>
> -    def mark_text(text)
> +    def self.mark_text(text)
>
> OK, I think what you want is "I want my base CLI class to help me with
> formatting". Make these public, instance methods, not "attempted private"
> class methods.
>
> Then, have ProfileGenerator inherit from here, or we make a real UI object.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/inspec/inspec/pull/3202#pullrequestreview-135535423>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABauaJs2VUpHPn-WZTpEHP065YM-eFQ9ks5uE6WSgaJpZM4VIISX>
> .
>

2018-07-13 21:52 UTC, clintoncwolfe commented
Adopted on #3214

2018-07-13 21:52 UTC, closed without merging