command resource: Allow redacting `#to_s`
inspec/inspec pull request #3207
Opened 2018-07-10 19:28 UTC by jerryaldrichiii

This allows the user to redact command arguments when using the `command` resource.

This also changes how the `#to_s` is rendered (adds a `:` and some backticks) let me know if that is too drastic of a change.

Examples:

```
# With capture groups
options = { redact_command: /(-p ).*( -d)/ }
describe command('myapp -p secretpassword -d no_redact', options) do
  its('exit_status') { should cmp 0 }
end

# Result (capture groups used)
Command: `myapp -p REDACTED -d no_redact`
          ✔  exit_status should cmp == 0

# Without capture groups
options = { redact_command: /-p .* -d/ }
describe command('myapp -p secretpassword -d no_redact', options) do
  its('exit_status') { should cmp 0 }
end

# Result (no capture groups used)
Command: `myapp REDACTED no_redact`
          ✔  exit_status should cmp == 0
```

This fixes https://github.com/inspec/inspec/issues/3185

2018-07-11 17:12 UTC, clintoncwolfe commented
Close/reopen to trigger re-run of travis job (another APT ephemeral failure)

2018-07-12 17:36 UTC, clintoncwolfe requested changes
I'd like to see the param name adjusted a bit (which I saw you asked for feedback on that), and maybe a bit more refining on the docs.  No serious complaints, easy to flip this to approved, just a bit of discussion.

2018-07-12 17:36 UTC, clintoncwolfe commented on docs/resources/command.md.erb
> +The following examples show how to use `redact_command` with the command resource:
You might want to omit the 'with the command resource' - it might be confusing (anything you do here is with the command resource).

2018-07-12 17:36 UTC, clintoncwolfe commented on docs/resources/command.md.erb
> +    options = { redact_command: /(-p ).*( -d)/ }
I might suggest not putting the options in a separate variable.  It's no big deal for ruby programmers, but non-developers might see that as part of the syntax.  You might inline it just to keep it clearer.

2018-07-12 17:36 UTC, clintoncwolfe commented on docs/resources/command.md.erb
> +    # Result (no capture groups used)
If possible you might show the simpler approach (no capture groups) first.  
If you feel that the no-capture approach is ugly or less  useful, we don't need to document it - we could present with-capture-groups as the only way.

2018-07-12 17:36 UTC, clintoncwolfe commented on docs/resources/command.md.erb
> +These sensitive parts can be redacted by passing in `redact_command` and a regular expression to redact. Optionally, you can use 2 capture groups to fine tune what is redacted.
For my $0.02, I think a short option name (`redact`, `redact_re`, `redact_regex`, `redact_output`) might be preferable.  You're already working with a `command` resource; that as a suffix might not add much information.

2018-07-12 17:36 UTC, clintoncwolfe commented on docs/resources/command.md.erb
> +These sensitive parts can be redacted by passing in `redact_command` and a regular expression to redact. Optionally, you can use 2 capture groups to fine tune what is redacted.
I think asking people to know what regexes are is one big step, and asking them to properly use capture groups is another big step - especially when they don't see how the implementation is using the capture groups.

We could link to a regexp playground app like [regexr](https://regexr.com).

There are several other ways to handle this - thoughts?

2018-07-12 17:36 UTC, clintoncwolfe commented on test/unit/resources/command_test.rb
> +    result.resource_exception_message.must_match /must be a regular expression/
I see you like regexes, so I put the string 'regular expression' in your regular expression

2018-07-12 17:56 UTC, jerryaldrichiii commented on docs/resources/command.md.erb
> +The following examples show how to use `redact_command` with the command resource:
Yup, good call. Fixing.

2018-07-12 17:57 UTC, jerryaldrichiii commented on docs/resources/command.md.erb
> +    options = { redact_command: /(-p ).*( -d)/ }
Hmmm...it was getting a bit long, but I agree. I'd rather have length over complexity.

2018-07-12 18:00 UTC, jerryaldrichiii commented on docs/resources/command.md.erb
> +    # Result (no capture groups used)
It's a bit ugly, but not dangerously so. I'll show it first since it is simpler.

2018-07-12 18:02 UTC, jerryaldrichiii commented on docs/resources/command.md.erb
> +These sensitive parts can be redacted by passing in `redact_command` and a regular expression to redact. Optionally, you can use 2 capture groups to fine tune what is redacted.
I wanted something to show we are just redacting the command that is printed. As opposed to stdout/stderr. You're right though. I think I'll go with `redact_regex` and rely on documentation.

2018-07-12 18:04 UTC, jerryaldrichiii commented on docs/resources/command.md.erb
> +These sensitive parts can be redacted by passing in `redact_command` and a regular expression to redact. Optionally, you can use 2 capture groups to fine tune what is redacted.
I thought the same, but didn't think about linking regexr. I think that is a solid idea. Will add.

2018-07-12 18:20 UTC, jerryaldrichiii commented on docs/resources/command.md.erb
> +    options = { redact_command: /(-p ).*( -d)/ }
Well...it renders really bad when I do it that way due to the line wrapping...I'm torn.

2018-07-12 18:27 UTC, clintoncwolfe requested changes

2018-07-12 18:27 UTC, clintoncwolfe commented on docs/resources/command.md.erb
> +    options = { redact_command: /(-p ).*( -d)/ }
Also, using `.*` is a bit dangerous - IIRC, star is greedy, so it will keep matching until the next atom matches. So if your redact is `/-p .*-d/` and you have `-p what --debug -d`, that will match out to `-p REDACTED -d`

I think you might want the minimal version, `.*?`.

2018-07-13 19:55 UTC, clintoncwolfe approved these changes
thanks @jerryaldrichiii !

2018-07-16 12:20 UTC, jquick approved these changes
Very nice! Thanks @jerryaldrichiii

2018-07-16 12:20 UTC, merged

2018-07-19 16:11 UTC, kplimack commented
Thanks @jerryaldrichiii

2018-07-20 18:19 UTC, kplimack commented
@jerryaldrichiii any chance of backporting this to inspec 1.x and releasing a gem?

unfortunately im stuck with an old version of chef that i cannot upgrade due to bugs/incompatibility with newer versions chef 

```
>>>> Caused by Gem::ConflictError: Unable to activate google-api-client-0.19.8, because addressable-2.4.0 conflicts with addressable (>= 2.5.1, ~> 2.5)
/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2290:in `raise_if_conflicts'
/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
```