Update `only_if` to allow user specified messages.
inspec/inspec pull request #3267
Opened 2018-08-01 22:37 UTC by miah

Updates only_if to allow a user to specify a message to say why it was skipped. If the user does not supply a message the default
message is used.

```
control 'nutcracker-connect-redis-001' do
  impact 1.0
  title 'Check if nutcracker can pass commands to redis'
  desc 'execute redis-cli set key command, to check connectivity of the service'

  only_if('redis is not installed.') do
    command('redis-cli').exist?
  end

  describe command('redis-cli SET test_inspec "HELLO"') do
    its(:stdout) { should match(/OK/) }
  end
end
```

```
  ↺  nutcracker-connect-redis-001: Check if nutcracker can pass commands to redis
     ↺  Skipped control due to only_if condition: redis is not installed.
```

Ref: https://github.com/inspec/inspec/issues/3158
Signed-off-by: Miah Johnson <miah@chia-pet.org>

2018-08-02 17:31 UTC, jquick reviewed
Really nice enhancement on this. I think we will also need to update: https://github.com/inspec/inspec/blob/ca1746debb0a3a1c72394e63b991ad8c111eb478/lib/inspec/rule.rb#L177 to set the `skip_rule[:result]` and maybe add a test for this case.

2018-08-08 18:45 UTC, aaronlippold commented
Fixes: https://github.com/inspec/inspec/issues/1900 - please add to commit message on merge so #1900 get closed.

2018-08-09 03:19 UTC, jerryaldrichiii requested changes
Looks great @miah only one small suggestion.

2018-08-09 03:19 UTC, jerryaldrichiii commented on lib/inspec/rule.rb
> +      if msg[:result].eql?(true) && msg[:message].nil?
You can remove the first criterion since we cannot reach here if `msg[:result]` is false. I'd also modify it a bit by changing `msg` to `skip_check` (or some better name...) then do the following:

```ruby
if skip_check[:message]
  msg = "Skipped control due to only_if condition: #{msg[:message]}"
else
  msg = "Skipped control due to only_if condition."
end

2018-08-09 17:19 UTC, clintoncwolfe approved these changes
Code looks good; tests are good on coverage but read a bit unclear too me.  Not a blocker. Thanks, @miah!

2018-08-09 17:19 UTC, clintoncwolfe commented on test/unit/profiles/profile_context_test.rb
>        let(:if_true) { "only_if { true }\n" }
For my part, having all of these brief `let`s containing short Strings is a bit confusing; if the lets were inlined, I think it would read clearer.  But that was already there.

2018-08-09 20:02 UTC, jerryaldrichiii approved these changes

2018-08-10 16:38 UTC, merged