adding a property of `file_count` to `directory` resource
inspec/inspec pull request #3403
Opened 2018-09-18 01:48 UTC by majormoses

This is helpful to support testing if a directory is empty, not empty or even in some cases matching a specific number.

While refactoring some chef changes I wanted to make sure that a particular directory includes no files as the client should not need them. They are needed on the server and the directory is automatically created on both client and server.

Signed-off-by: Ben Abrams <me@benabrams.it>

2018-09-18 01:54 UTC, majormoses commented
Looks like the same transient issue as I encountered here https://github.com/inspec/inspec/pull/3398#issuecomment-421523635 if you can kick appveyor again and see if it resolves that would be great.

2018-09-25 16:04 UTC, clintoncwolfe submitted a review, later dismissed
So straightforward, I don't think it even needs a test.  And you included docs!  Thanks!

2018-09-26 13:34 UTC, jquick requested changes
Thanks for the PR @majormoses. Unfortunately I think we need to revisit this implementation and make sure it works for both local and remote transports.

2018-09-26 13:34 UTC, jquick commented on lib/resources/directory.rb
> +      Dir.entries(file).reject { |f| f == '.' || f == '..' }.count
Using a Dir.entries will only work on the local transport. Even then I am getting errors using this like:
```
(master)> _inspec exec file_count.rb

Profile: tests from file_count.rb (tests from file_count.rb)
Version: (not specified)
Target:  local://

  Directory /tmp
     ✔  should exist
     ✔  should be directory
     ×  file_count
     no implicit conversion of Train::File::Local::Unix into String
```
Changing it to `file.path` fixes the issue for local but will cause unexpected results when using a remote target. I think we need to add more logic into train if we want to do this: https://github.com/inspec/train/tree/master/lib/train/file. Adding a Directory class in Train would be a good start i think.

2018-09-26 19:24 UTC, clintoncwolfe commented on lib/resources/directory.rb
> +      Dir.entries(file).reject { |f| f == '.' || f == '..' }.count
Goooood catch, @jquick.

2018-09-27 15:14 UTC, jquick commented
Since this will require some pre-work in inspec/train I am closing this PR for now. Once we have the proper setup in Train we can then implement it here. Thanks again for your help and involvement!

2018-09-27 15:14 UTC, closed without merging

2018-10-03 00:58 UTC, majormoses commented
@jquick sorry for the late response and good catch, is there an issue to add the required bits to train?

2018-10-03 13:01 UTC, jquick commented
Hey @majormoses - I created https://github.com/inspec/train/issues/360 to track this.