Add missing tests for groups resource, document members property, and assorted fixes.
inspec/inspec pull request #3467
Opened 2018-10-05 00:43 UTC by miah

Please let me know if I missed anything. This should improve tests around the group resource and fix missing documentation as noted in #3422 

Changes:
Update existing documentation for group resource.
Add documentation for groups resource.
Update group resource tests to test members property.
Change groups resource members property to have simple style. (this
ensures members is a single array)
remove deprecated have_gid propery.
change `if !` to `unless`
Remove early return from members method. This prevented members from
working correctly on any OS other than Windows.
Add missing tests for the groups resource.

Fixes https://github.com/inspec/inspec/issues/3422

2018-10-10 19:46 UTC, jerryaldrichiii requested changes
Just one tiny change.

2018-10-10 19:46 UTC, jerryaldrichiii commented on docs/resources/groups.md.erb
> +# group
Should be `groups`, right?

2018-10-18 20:14 UTC, jquick approved these changes
Thanks @miah

2018-10-18 20:33 UTC, jerryaldrichiii approved these changes

2018-10-18 20:48 UTC, merged