add aws_eks_cluster
inspec/inspec pull request #3504
Opened 2018-10-12 12:19 UTC by j00p34

Signed-off-by: Timothy van Zadelhoff
timothy.inspec@theothersolution.nl

feature request

I would like to use inspec to test and monitor an AWS EKS cluster

Please review my pull request to add the aws resource aws_eks_cluster

2018-10-15 17:11 UTC, clintoncwolfe requested changes
This is very, very good work!  Thank you so much, @j00p34 !

There are some nice-to-haves, like adding matchers for the status states, and a few docs tweaks. 

However, the major missing piece is integration tests.  We typically include Terraform code to setup the object under test, and then run live-fire tests against it.  See test/integration/aws/ for details.  I may be able to assist with that testing, if you are unable.  Thanks again!

2018-10-15 17:11 UTC, clintoncwolfe commented on docs/resources/aws_eks_cluster.md.erb
> +### Version
You can just omit this section; we'll inject it with tooling later at release-time.

2018-10-15 17:11 UTC, clintoncwolfe commented on docs/resources/aws_eks_cluster.md.erb
> +      its('version') { should eq '1.5' }
For better or worse, we usually use `cmp` in examples like this.  cmp has sloppy typecasting behavior, so it would match `1.5`, `'1.5'`, and even `:'1.5'`.

2018-10-15 17:11 UTC, clintoncwolfe commented on docs/resources/aws_eks_cluster.md.erb
> +Returns a string containing the current status of the cluster, possible values are: CREATING,ACTIVE,DELETING,FAILED
I think you should also (or instead) expose these as matchers.  In your implementation, you'd define 4 predicate methods, `creating?`, `active?`, etc which return true or false.

You'd document these under the Matchers section, with examples:

```
describe aws_eks_cluster('mine') do
 it { should be_active }
end
```

Little things like this are how we make InSpec more "fluent" than the underling API.

2018-10-15 17:11 UTC, clintoncwolfe commented on docs/resources/aws_eks_cluster.md.erb
> +Returns an string with the K8s API server endpoint. The endpoint is used by kubectl to control the cluster
Missing a '.' at the end :-)

2018-10-15 17:11 UTC, clintoncwolfe commented on docs/resources/aws_eks_cluster.md.erb
> +Returns an array of strings reflecting the security group IDs (firewall rule sets) assigned to the EKS Cluster VPC.
Well handled.

2018-10-15 17:11 UTC, clintoncwolfe commented on docs/resources/aws_eks_cluster.md.erb
> +### Test that an EKS Cluster has at least 2 subnets
It looks like EKS has a rich set of touchpoints with other InSpec AWS resources, such as VPC, Security Group, and Subnet.  You might consider a richer example showing how to use the resources in lookup (non-test) mode in an integrated way:

```
# Ensure that your EKS cluster is not in the default security group

# This performs a data lookup, not a test
default_security_group = aws_security_group('default')

describe aws_eks_cluster('my-cluster') do
  its('security_group_ids') { should_not include default_security_group.security_group_id }
end

```

2018-10-15 17:11 UTC, clintoncwolfe commented on docs/resources/aws_eks_cluster.md.erb
> +The documentation for EKS actions is at [Policy Structure](https://docs.aws.amazon.com/eks/latest/userguide/iam-policy-structure.html#UsingWithEKS_Actions)
Great docs, good job!

2018-10-15 17:11 UTC, clintoncwolfe commented on test/unit/resources/aws_eks_cluster_test.rb
> +    assert_equal('kang-the-alien', cluster.name)
I voted for Kodos.

2018-10-15 17:11 UTC, clintoncwolfe commented on test/unit/resources/aws_eks_cluster_test.rb
> +end
Fantastic unit test!

2018-10-15 18:08 UTC, j00p34 commented
@clintoncwolfe first: Thank you for your review, valid points. Second: I'll try to do the requested changes tomorrow. Except for the Terraform that will be later this week, I'm currently using it with TF so I don't expect big problems with it. I'll have to adapt it to your test environment though, that'll take me a little more time.

2018-10-17 07:41 UTC, j00p34 commented on docs/resources/aws_eks_cluster.md.erb
> +### Version
done

2018-10-17 07:41 UTC, j00p34 commented on docs/resources/aws_eks_cluster.md.erb
> +      its('version') { should eq '1.5' }
done

2018-10-17 07:43 UTC, j00p34 commented on docs/resources/aws_eks_cluster.md.erb
> +Returns a string containing the current status of the cluster, possible values are: CREATING,ACTIVE,DELETING,FAILED
I chose to keep the original one as well, as it allows a little more flexibility

2018-10-17 07:44 UTC, j00p34 commented on docs/resources/aws_eks_cluster.md.erb
> +Returns an array of strings reflecting the security group IDs (firewall rule sets) assigned to the EKS Cluster VPC.
thnx

2018-10-17 07:44 UTC, j00p34 commented on docs/resources/aws_eks_cluster.md.erb
> +### Test that an EKS Cluster has at least 2 subnets
done

2018-10-17 07:44 UTC, j00p34 commented on test/unit/resources/aws_eks_cluster_test.rb
> +    assert_equal('kang-the-alien', cluster.name)
I'm sorry. Kodos failed

2018-10-17 07:46 UTC, j00p34 commented on test/unit/resources/aws_eks_cluster_test.rb
> +end
Thnx again :-)

2018-10-17 10:31 UTC, j00p34 commented
@clintoncwolfe PTAL

2018-11-05 22:53 UTC, clintoncwolfe commented
Flagging for adoption: the docs, code, and unit tests are really great.  The integration tests are too good, using features of Terraform that the rest of the AWS integration tests don't, in an incompatible way.  #3578 was created to track updating the tests to be as good as what @j00p34 provided; in the meantime, I'm adopting the PR, and will walk the tests back to be more compatible.

2018-11-06 23:30 UTC, clintoncwolfe commented
Thanks @j00p34 !  The PR has been adopted as #3582.

2018-11-06 23:30 UTC, closed without merging