Add support for relative paths to the Git fetcher
inspec/inspec pull request #3522
Opened 2018-10-17 05:10 UTC by jerryaldrichiii

This adds support for specifying a path to a profile in a Git repo.

For example, you could have a Git repo containing multiple profiles and you want to specify a single one like below:

```yaml
depends:
  - name: profile-1
    git: https://github.com/myorg/all-my-profiles.git
    profile_path: profiles/my-specific-profile-1
  - name: profile-2
    git: https://github.com/myorg/all-my-profiles.git
    profile_path: profiles/my-specific-profile-2
```

This closes #2167 
This closes #1974 
This closes #1237

2018-10-17 05:12 UTC, jerryaldrichiii commented
@trevor-vaughan (and InSpec team) let me know what you think. I'm not set on `profile_path` as the UX, I've seen `directory`, `rel`, and `path` I believe.

2018-10-17 10:29 UTC, trevor-vaughan commented
@jerryaldrichiii Honestly, out of those, `profile_path` is the most descriptive to a new user in my opinion.

`directory` is my second choice, `rel` doesn't make any sense to me, and `path` feels like it could be anywhere on the system.

Alternatively, something like `subdirectory` would also be more descriptive.

All that said, I think that it would be valuable to make `profile_path` a path relative to the checkout by default but also allow for a full filesystem path without specifying a `git` target. That way users can target random things on their OS for testing and it may also come in handy for different non-Internet CI/CD scenarios.

2018-10-17 10:36 UTC, trevor-vaughan reviewed
:+1:

2018-11-13 21:09 UTC, chris-rock commented
I like that functionality 👍 

There are still a few things to think about and we should have clear answers to those. e.g As https://github.com/inspec/inspec/issues/1237 highlights, many profiles can reside in a git repo, therefore we need to think about how this profile can be executed directly too. If `inspec exec git` is pointed to a mono-repo, how should it behave? Should it say, no profile found, should it run all profiles? Do we need a cli flag to provide the relative profile path? What happens if I have a mono-repo in git and I point `inspec` to its tar representation? What happens if the profiles have relative dependencies within the same git repo? Probably you want to use a relative path in the inspec yml, to ensure it works with local paths. I think we need a consistent story.

2018-11-28 19:32 UTC, trevor-vaughan commented
As a point to note, this is the last thing that I need to be able port my profile into https://github.com/complianceascode/content

Responses to points by @chris-rock below:

> There are still a few things to think about and we should have clear answers to those. e.g As #1237 highlights, many profiles can reside in a git repo, therefore we need to think about how this profile can be executed directly too.

AFAIK, you can already do that by just pointing to the directory.

> If inspec exec git is pointed to a mono-repo, how should it behave? Should it say, no profile found, should it run all profiles? 

Provide a list of discovered profiles and allow the user to select one (or more). Have a command line switch that allows selection of profiles from a mono-repo by name.

> Do we need a cli flag to provide the relative profile path?

Probably, yes.

> What happens if I have a mono-repo in git and I point inspec to its tar representation?

Same as above, it prompts you for the ones that you want to run unless you specify them at the command line. For an easier to implement version, it could just print what you have available and then tell you what command line flag to add so that it's less interaction and debugging.

> What happens if the profiles have relative dependencies within the same git repo?

Wouldn't these be resolved at run time and, given that they're all together, work just fine?

> Probably you want to use a relative path in the inspec yml, to ensure it works with local paths.

Yes, this makes the most sense. Doing anything else binds you to the internet anyway and is almost always incorrect for secure environments.

2018-11-29 18:19 UTC, clintoncwolfe commented
FWIW, #3618 provides rich prompting capabilities
Also refs #3297 for airgap support

2018-12-08 22:19 UTC, aaronlippold commented
Are there still open changes that need to take place on this PR or are we just waiting on a review?

2018-12-12 18:18 UTC, clintoncwolfe commented
Removing DNM flag: ready for review for potential merge

2018-12-20 13:38 UTC, bdwyertech approved these changes
Looks good to me.  I'll start looking at this from the `kitchen-inspec` perspective

2019-02-26 19:35 UTC, clintoncwolfe requested changes
Thanks @jerryaldrichiii! I think in a situation with many different use cases, we need to be careful to test the majority of them.  So, that's the main request - test more and different situations.

2019-02-26 19:35 UTC, clintoncwolfe commented on test/functional/gitfetcher_test.rb
> +    @profile_dir = File.join(@tmpdir, 'test-profile')
Might suggest naming this 'top-level-profile'.  All of these are test profiles.

2019-02-26 19:35 UTC, clintoncwolfe commented on test/functional/gitfetcher_test.rb
> +      out = inspec("exec #{@profile_dir} " \
Try to use `run_inspec_process` when writing new functional tests. It has options like CWD, JSON output, no lockfile by default, etc.

2019-02-26 19:35 UTC, clintoncwolfe commented on test/functional/gitfetcher_test.rb
> +      inspec('init profile ' + File.join(deep_profiles, 'deep-profile'))
Try to use `run_inspec_process` when writing new functional tests. It has options like CWD, etc.

2019-02-26 19:35 UTC, clintoncwolfe commented on test/functional/gitfetcher_test.rb
> +  it 'executes a profile with a git based dependencies' do
I think this is under-tested.  As @chris-rock mentioned on the PR commentary, there are several distinct use cases to examine here, and only one is attempted (though it is a complex one).

I'd like to see more use cases tested.  For example, this doesn't test the case in which there are multiple profiles in a git repo, and only one is wanted.

2019-02-26 19:35 UTC, clintoncwolfe commented on docs/profiles.md
> +  profile_path: optional/path/to/profile
Maybe `optional/relative/path/within/repo`?

2019-02-26 19:35 UTC, clintoncwolfe commented on docs/profiles.md
> +  profile_path: optional/path/to/profile
Hrm, we actually have a bit of a naming conflict.  `path` is a valid key here, and specifies to use the local file fetcher. `profile_path` is only valid if `git` is also present, and indicates the path within the repo.

`path_within_repo`?

2019-02-26 19:35 UTC, clintoncwolfe commented on lib/fetchers/git.rb
> +      @target_profile_path = opts[:profile_path]
It might be better to avoid using the word 'target' in new code, unless you are specifically referring to the scanning target.

2019-03-11 12:16 UTC, stevendanna commented on lib/fetchers/git.rb
> +      @target_profile_path = opts[:profile_path]
The rest of this PR has a good deal of conditional logic here.  I'm wondering if that conditional logic could be removed by making the _default_ profile_path `./`.  This of course depends on what behavior we want when someone happens to point at a git repository with multiple profiles.

2019-03-11 16:21 UTC, jerryaldrichiii commented
Hey all, given my job change I won't have time to work on this PR.

Feel free to adopt and make any changes needed :smile:

2019-03-15 15:12 UTC, clintoncwolfe commented on docs/profiles.md
> +  profile_path: optional/path/to/profile
Today 'relative_path' feels good.

2019-05-14 17:19 UTC, miah requested changes
Needs adoption.

2019-06-12 00:48 UTC, kekaichinose commented
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

2019-06-13 00:28 UTC, kekaichinose commented
Reopening because I wasn't fully up to speed on ask here, and since the PR addresses the OP's problem. Let's review this and get this out the door.

2019-06-19 16:44 UTC, clintoncwolfe commented
This PR has been adopted on #4217 - closing this one. Thanks @jerryaldrichiii!

2019-06-19 16:44 UTC, closed without merging