ksh support
inspec/inspec pull request #3533
Opened 2018-10-21 14:08 UTC by aklyachkin

Trivial change - added support for ksh (Korn Shell) resource.

2018-10-22 21:23 UTC, jerryaldrichiii requested changes
Thank you for your first contribution @aklyachkin! Only a few suggestions.

In addtion to removing the author lines, could you also do DCO sign off by doing a `git commit --amend -s`? This is a little beyond a Chef's "Obvious Fix" policy I believe, see: https://docs.chef.io/community_contributions.html#the-obvious-fix-rule

For more info on DCO you can check out: https://github.com/inspec/inspec/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

2018-10-22 21:23 UTC, jerryaldrichiii commented on test/unit/resources/ksh_test.rb
> +# author: Christoph Hartmann
Could you remove these author lines? We track authorship via Git so no need to replace them.

2018-10-22 21:33 UTC, aklyachkin commented
Hi, I changed both things. Although I still think it's quite trivial - i just took bash resource and changed two letters in it ;-)

2018-10-23 00:17 UTC, jerryaldrichiii approved these changes

2018-10-23 00:18 UTC, jerryaldrichiii commented
I can see that argument :smile: couldn't hurt to have the sign off though. Better safe than sorry.

2018-10-23 13:15 UTC, jquick approved these changes
Looks good to me! Thanks @aklyachkin

2018-10-23 13:16 UTC, merged