Fixing #3563; freebsd is not a substring of 'bsd'
inspec/inspec pull request #3565
Opened 2018-11-01 13:12 UTC by dijit

I understand this is rather zealous, since it will match openbsd- but at least it will allow FreeBSD to work, since we have code for that already.

2018-11-01 13:49 UTC, dijit commented
Nvm, simply dropping the brackets solved the issue too.

2018-11-01 16:59 UTC, clintoncwolfe commented
Thanks @dijit!  Could you take a moment and sign your commits using `git commit -s`?  We use commit signing to indicate that the contributor has read and understood the [Developer Certification of Origin](https://github.com/inspec/inspec/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco), which basically means it's your code you're contributing, it doesn't introduce a new license, etc.  Thanks!

2018-11-01 17:11 UTC, jquick approved these changes
Thanks @dijit

2018-11-01 17:14 UTC, clintoncwolfe requested changes
Thanks for the contribution! However, I think the test that is being used could be made safer. It's not obvious how to do that, so I've asked our platform detect expert to weigh in.

2018-11-01 17:14 UTC, clintoncwolfe commented on lib/resources/port.rb
> +      elsif 'freebsd'.include?(os[:family])
@jquick do we auto-generate predicates for each platform?  If so, we could have `os.freebsd?`.

`os[:family]` is 'bsd' here, which is correct; the platform would be `freebsd`.  I think relying on the fact that one is a substring of the other is not the intent of the code - we are asking specifically if we are on freebsd.

So I agree we need a conditional to match FreeBSD, but I think it should be something higher-level like `os.freebsd?`.

2018-11-01 20:27 UTC, jquick commented on lib/resources/port.rb
> +      elsif 'freebsd'.include?(os[:family])
Yes with the new platforms work `os.freebsd?` should work as expected.

2018-11-05 22:59 UTC, clintoncwolfe commented
As this is a one-line change, I'm going to adopt it to add the os-based predicate call.

2018-11-05 23:57 UTC, clintoncwolfe commented
Hrm, looks like we don't get platform-name-specific predicates automatically.  I spun up a freebsd 9.3 vagrantbox from our Kitchen config, and played:

```
[cwolfe@lodi inspec-review]$ be inspec version
3.0.28
[cwolfe@lodi inspec-review]$ be inspec detect -t ssh://vagrant@127.0.0.1:2222

== Platform Details

Name:      freebsd
Families:  bsd, unix, os
Release:   9.3-RELEASE-p49
Arch:      amd64
[cwolfe@lodi inspec-review]$ be inspec shell -t ssh://vagrant@127.0.0.1:2222 -c 'os.freebsd?' 2>&1 | head -2
bundler: failed to load command: inspec (/Users/cwolfe/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bin/inspec)
NoMethodError: undefined method `freebsd?' for Operating System Detection:#<Class:0x00007ff2fed65d28>
[cwolfe@lodi inspec-review]$ be inspec shell -t ssh://vagrant@127.0.0.1:2222 -c 'os.bsd?'
true
[cwolfe@lodi inspec-review]$ be inspec shell -t ssh://vagrant@127.0.0.1:2222 -c 'os.name'
freebsd
[cwolfe@lodi inspec-review]$ be inspec shell -t ssh://vagrant@127.0.0.1:2222 -c 'os.family'
bsd
```

It does appear that sockstat (the CLI tool that the code relies on) is standard on NetBSD.  I think changing the conditional to be `os.bsd?` would be OK.

2018-11-06 00:12 UTC, clintoncwolfe commented
Adopted on #3579; thanks again for your contribution!

2018-11-06 00:12 UTC, closed without merging