Fix inspec wrapper linking to /bin/bash instead of the bash hab package
inspec/inspec pull request #3671
Opened 2018-12-14 22:03 UTC by teknofire

Adds missing `pkg_deps` for `core/bash`, otherwise
https://github.com/inspec/inspec/blob/master/habitat/plan.sh#L57 would
return an empty string for the pkg path and output `/bin/bash`
instead of the expected `/hab/pkgs/core/bash/.../bin/bash` path.

Signed-off-by: Will Fisher <wfisher@chef.io>

2018-12-18 20:09 UTC, jerryaldrichiii requested changes
Great catch @teknofire!

We did something slightly unconventional and removed hab dependencies and instead modified InSpec to use system packages (see https://github.com/inspec/inspec/blob/master/habitat/plan.sh#L62). That being said, ensuring we have an interpreter to read our bin wrapper is crucial. I mistakenly thought this was provided by `core/coreutils`.

Care to change the line below to `pkg_path_for core/bash` instead of just `pkg_path_for bash`?

https://github.com/inspec/inspec/blob/master/habitat/plan.sh#L57

2018-12-20 18:19 UTC, teknofire commented
@jerryaldrichiii updated with the requested change

2018-12-20 18:25 UTC, jerryaldrichiii approved these changes
Great catch @teknofire!

2018-12-20 18:27 UTC, clintoncwolfe approved these changes
Thanks!

2018-12-20 18:29 UTC, merged