Promote Hab package alongside Omnibus package
inspec/inspec pull request #3728
Opened 2019-01-15 21:19 UTC by schisamo

This change ensures we are promoting our Hab packages to `current` and
`stable` at the same time we execute said promotions for the Omnibus
packages.

Signed-off-by: Seth Chisamore <schisamo@chef.io>

2019-01-15 21:29 UTC, tduffield requested changes
Blocked by https://github.com/chef/expeditor/issues/870

2019-01-17 18:12 UTC, miah approved these changes
Seems reasonable to me. Thanks @schisamo

2019-01-18 18:32 UTC, tduffield approved these changes

2019-01-18 19:18 UTC, jerryaldrichiii approved these changes
Looks good to me. Is this still blocked?

2019-01-18 19:19 UTC, jerryaldrichiii commented
Once this is merged we should update our release instructions, since right now we do this manually.

2019-01-22 18:23 UTC, merged