Add `--help` to CLI plugin activation criteria
inspec/inspec pull request #3757
Opened 2019-01-26 20:50 UTC by jerryaldrichiii

This ensures that all the following result in the same CLI output:
  - `inspec`
  - `inspec help`
  - `inspec --help`

This closes #3753.

2019-01-28 01:23 UTC, clintoncwolfe requested changes
Thanks for the quick response on this, @jerryaldrichiii ; just need to consolidate a duplicated test, and make sure we are testing the right thing.  Thanks!

2019-01-28 01:23 UTC, clintoncwolfe commented on lib/inspec/plugin/v2/loader.rb
> +        activate_me ||= ['help', '--help', nil].include?(cli_args.first)
This seems a bit less clear, but I think we can live with it.

2019-01-28 01:23 UTC, clintoncwolfe commented on test/functional/inspec_test.rb
> +    it 'outputs the same message when using `help`, `--help`, or no args' do
This test (though missing --help) already exists at https://github.com/inspec/inspec/blob/fd0ef925c4e32c68e42cbaf449f49b09b198a2f9/test/functional/plugins_test.rb#L71

Arguably it should be in `inspec_test.rb`, as you have it , but it shouldn't be in both places.  Could you consolidate them?

2019-01-28 01:23 UTC, clintoncwolfe commented on test/functional/inspec_test.rb
> +      outputs.uniq.length.must_equal 1
Ahh, this test says "all three of these should say the same message, but we don't care what the contents of the message are".  

In fact, we very much do care - the OP on #3753 reported that `init` was missing from the output.  You can do something like https://github.com/inspec/inspec/blob/fd0ef925c4e32c68e42cbaf449f49b09b198a2f9/test/functional/plugins_test.rb#L76 to verify that plugins are indeed being loaded.

2019-01-28 01:38 UTC, jerryaldrichiii commented on test/functional/inspec_test.rb
> +    it 'outputs the same message when using `help`, `--help`, or no args' do
Sure can! Great catch.

2019-01-28 04:44 UTC, clintoncwolfe approved these changes
Thanks!

2019-01-31 18:27 UTC, miah approved these changes

2019-01-31 20:54 UTC, merged