Use deprecation facility throughout code
inspec/inspec pull request #3829
Opened 2019-02-22 08:24 UTC by jerryaldrichiii

This converts all current deprecation warnings/TODOs to use the `Inspec.deprecate()` deprecation facility.

This also modifies `Inspec.deprecate()` to only require 1 argument.

This closes #3745

2019-02-27 00:11 UTC, miah approved these changes
Legit. Thanks @jerryaldrichiii

2019-02-27 20:13 UTC, clintoncwolfe requested changes
Thanks for all this @jerryaldrichiii - we'll be adopting it.  

Most of my changes are around specificity of the deprecation group names; and an idea around reducing the amount of test changes we'd need to do.

2019-02-27 20:13 UTC, clintoncwolfe commented on etc/deprecations.json
> +  "unknown_group_action": "exit",
Did you intend to commit this?  I often set this during development, but I think in a release it would be safer to have this be `ignore`.

2019-02-27 20:13 UTC, clintoncwolfe commented on etc/deprecations.json
> +      "action": "ignore",
might add comment refs #3715

2019-02-27 20:13 UTC, clintoncwolfe commented on lib/inspec/config.rb
> +      Inspec.deprecate(:cli_option_json_config) if cli_opts.key?(:json_config)
💯

2019-02-27 20:13 UTC, clintoncwolfe commented on lib/matchers/matchers.rb
> +    Inspec.deprecate(:serverspec_compatibility, 'The service `be_running?` matcher is deprecated.')
I think this group name should probably be more specific. While we are reprioritizing serverspec compatibility, I don't think we're ripping it out all at once, either.

2019-02-27 20:13 UTC, clintoncwolfe commented on lib/resources/aws/aws_iam_user.rb
> +    Inspec.deprecate(:properties_aws_iam_user, 'The aws_iam_users `name` property is deprecated. Please use `username` instead')
Typo in the message here - this is in the `aws_iam_user` resource, but teh message refers to the plural.

2019-02-27 20:13 UTC, clintoncwolfe commented on lib/resources/filesystem.rb
> -      Inspec.deprecate(:filesystem_property_size, 'The `size` property did not reliably use the correct units.  Please use `size_kb` instead.')
I don't know that it's worth renaming them all, but RESOURCENAME_WHAT_NAME reads better to me than WHAT_RESOURCENAME_NAME.

2019-02-27 20:13 UTC, clintoncwolfe commented on lib/resources/host.rb
> +        Inspec.deprecate(:host_resource_proto_usage, 'The host resource `proto` parameter is deprecated. Please use `protocol`.')
proto_param - these are called resource parameters.

2019-02-27 20:13 UTC, clintoncwolfe commented on lib/resources/users.rb
> +      Inspec.deprecate(:resource_user, 'The user resource `minimum_days_between_password_change` property is deprecated. Please use `mindays`.')
I'd change all of these to something like :user_resource_serverspec_compat .  Makes the intent and scope more explicit.

2019-02-27 20:13 UTC, clintoncwolfe commented on lib/utils/parser.rb
> +      Inspec.deprecate(:serverspec_compatibility, 'Parsing mount options in this fashion is deprecated')
This should def. be more specific.

2019-02-27 20:13 UTC, clintoncwolfe commented on test/helper.rb
> +  @mock_logger = Minitest::Mock.new
Does this actually need to be an instance variable?

2019-02-27 20:13 UTC, clintoncwolfe commented on test/helper.rb
> +def expect_deprecation_warning
We might want to make this looser - like `expect_deprecation_action(opts)`.  With no args, it expects that `Inspec.deprecate` will be called at least once.  With args, we might insist on a particular action, or restrict which group names we expect to see.

The goal here would be that a deprecation will naturally progress through ignore, warn, fail/exit over its life, letting us change the test code less frequently.  If we use a more general check like this, we would not be insisting on a warning, just a check that we know it is scheduled for deprecation.

@miah, thoughts?

2019-04-16 21:40 UTC, clintoncwolfe commented
Superceded by #3952

2019-04-16 21:40 UTC, closed without merging