Enhanced inspec/train to add addition platform information for Linux
inspec/inspec pull request #3885
Opened 2019-03-11 14:16 UTC by kevin-j-smith

inspec/train enhanced to add hostname, domainname, fqdn and network to the platform section of it's os export.  Added logic to properly handle and report these findings.

#3869

2019-03-11 14:18 UTC, kevin-j-smith commented
This commit will be more impactful once inspec/train has accepted PR: inspec/train#418 https://github.com/inspec/train/pull/418

2019-03-12 18:38 UTC, clintoncwolfe requested changes
Thanks for the contribution!

However, as discussed on #3869, we'd rather see the network identifiers collected by something an Ohai resource, or something else - not from platform.

Additionally, in its final form, we generally expect tests and documentation to be included with PRs.  Thanks!

2019-03-12 18:38 UTC, clintoncwolfe commented on lib/inspec/formatters/base.rb
> +        network: platform(:network),
As commented on #3869, I really think this data should come from something like an Ohai resource (see #3886). You can access resources even in places like this by using the Resource Registry.

2019-03-12 18:38 UTC, clintoncwolfe commented on lib/resources/platform.rb
> +    %w{family release arch network hostname fqdn domain_name guid}.each do |property|
As mentioned elsewhere, I don't think this should be added to platform.

2019-04-10 15:28 UTC, clintoncwolfe commented
(boilerplate message)
Hi! This PR has been untouched for more than two weeks, in the "Changes Requested" state. Please either make the requested changes, or continue the discussion in comments.

2019-06-12 00:49 UTC, kekaichinose commented
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

2019-06-12 00:49 UTC, kekaichinose commented
Sorry, prematurely pulled the trigger on this. Reopening.

2019-06-18 14:10 UTC, clintoncwolfe commented
We're going to go ahead and close this, as it now has merge conflicts, hasn't been updated, and we've updated the originating issue with next steps. Thanks!

2019-06-18 14:10 UTC, closed without merging