Add parameter '--sort_files' for 'inspec exec' to sort files before
inspec/inspec pull request #3887
Opened 2019-03-13 18:36 UTC by mschmeitz

Add parameter '--sort_files' for 'inspec exec' to sort files before executing controls.

Often controls filenames are numbered, sorting them makes the output
logical instead of randomized.

This also enables our use case: Running inspec with attributes file
'exceptions.yml' that contains exceptions. The profile controls folder
contains files like file-01.rb, file-02.rb etc. and a zzSkip_Control.rb
This last file contains no tests, only logic that iterates over all
controls; When a control is defined in an (--attrs) exceptions file it
will be skipped.

This enables a multi layered model; controls defined in exceptions.yml
are skipped during the profile handling, instead of the skip_control
examples that require a 'master' profile to skip exceptions in 'child'
profile.

Also, the 'master'-'child' model only can handle a single layer, the
multi layer model can have multiple layers; layer 3 profile (the one
that is executed) depends on layer 2 profiles, depends on layer 1
profiles. The skip_control is available on each layer when using the
technique as described above.

Signed-off-by: Mike Schmeitz <mike.schmeitz@ictelligent.nl>

2019-03-13 18:38 UTC, mschmeitz commented
replaces #3840

2019-03-13 23:27 UTC, clintoncwolfe requested changes
This looks pretty good, and is a straightforward implementation.  However, we need to have some functional testing on this.  Have a look at the functional tests in `test/functional/inspec_exec_test.rb` (and I would encourage you to use the `run_inspec_process` helper method, rather than the older `inspec` method).

Some cases I'd like to see covered:
 - a flat profile with ~10 control files executes them in no particular order when the --sort-files option is absent
 - a flat profile with ~10 control files executes them in collation order when the --sort-files option is present
 - a profile that wraps another profile loads files in ... some defined way when the --sort-files option is present.

Thanks! The third test case is especially important - we need to have well-defined behavior when adding new features.

2019-03-31 11:08 UTC, clintoncwolfe commented
(boilerplate message)
Hi! This PR has been untouched for more than two weeks, in the "Changed Requested" state. Please either make the requested changes, or continue the discussion in comments.

2019-04-01 17:20 UTC, mschmeitz commented
Added tests using dependent profiles: they failed! 
Haven't had (enough) time to fix this.  My time constraint and the fact that this sort option is not mandatory at this moment makes that I don't take action on this PR. From my side, this PR can be closed.

2019-04-03 17:51 UTC, aaronlippold commented
I don't see the tests pushed to the PR. If you push the tests - even if broken - I can take a look at fixing them.

2019-04-04 17:48 UTC, mschmeitz commented
@aaronlippold I have updated the PR and included the tests. There is a readme file that lists the structure, you should run the /test/unit/mock/profiles/sort-controls/profile_layer_top

My requirement is that files within a single profile (even when it is a dependency  profile), executes the tests in a sorted manner, where file sorting is sufficient.

Current setup only sorts the first profile but not its dependencies. I was not (yet?) able to parse the sort parameter to the profiles that are handled as dependency.

I do appreciate your help and am willing to anticipate if I can!

2019-04-05 13:37 UTC, aaronlippold commented
My guess it is when we have dependent profiles we have to have some sort of
recursion going on that you're calling sort on each dependent profile down
the chain and then finally sorting the primary profile.



On Thu, Apr 4, 2019, 1:48 PM mschmeitz <notifications@github.com> wrote:

> @aaronlippold <https://github.com/aaronlippold> I have updated the PR and
> included the tests. There is a readme file that lists the structure, you
> should run the /test/unit/mock/profiles/sort-controls/profile_layer_top
>
> My requirement is that files within a single profile (even when it is a
> dependency profile), executes the tests in a sorted manner, where file
> sorting is sufficient.
>
> Current setup only sorts the first profile but not its dependencies. I was
> not (yet?) able to parse the sort parameter to the profiles that are
> handled as dependency.
>
> I do appreciate your help and am willing to anticipate if I can!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/inspec/inspec/pull/3887#issuecomment-479997613>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABauaJ0zULWCV51X_o402egyuovtxJMTks5vdjsIgaJpZM4bvUu->
> .
>

2019-04-18 13:14 UTC, aaronlippold commented
Ping, I plan on putting folks on this in the next week.

2019-05-07 19:02 UTC, mschmeitz commented
It has been a while and I think I wanted to take a short cut with the 'sort-files' option. What our organization really needs is handling exceptions when using inherited profiles. 

The idea we have is to use a 3 layered model. 
- The 3rd and bottom layer contains the controls, for example the complete CIS baseline, additional SSH tests, tests for Jenkins, tests created by DevOps teams, tests downloaded from (and maintained on) the internet etc. 
- The 2nd layer 'cherry picks' these controls, filters unwanted tests, and bundles them together using skips/requires. 
- The 1st layer combines the profiles of the 2nd layer. So we fire one profile, that profile belongs to a specific type of infra component (call it building block, role, like a web server, proxy server etc). The web server profile contains 'CIS profile', 'webserver security profile', 'generic company wide security profile', 'webserver buildingblock profile' 

So for the infra component 'web server' a set of 2nd layer profiles is defined, one of these profiles contains 'CIS profile' with a, by the organization, defined set of controls. And, one control that must be applicable is 'no HTTP deamon'. This is fine on most servers but is not relevant (and conflicts) on web servers. So we either need to remove the 2nd layer (which is very cumbersome; when we want to add 1 control we need to update all the profiles). 

As an alternative we can define the controls as exceptions in an exception.yaml file. At execution we parse that file using the 'attributes' option and then it 'iterates' over *ALL* the controls (*in all profiles*), and assigns the exceptions as 'skip_control' to have no fails. (See the start of this thread, here's the need for sorting).  

But what we really need is that we can add exceptions, to filter controls that reside on the 3rd layer (i.e. on the child of the child of the parent profile).

Since that feature (gather all controls including inherited, and then filter based on exception.yaml) is far more complicated as 'sort files', and the fact that I can deliver my use case with 'sort files', my choice was to go for the 'sort files' option.

2019-05-07 20:35 UTC, clintoncwolfe commented
I can understand wanting `--sort-control-files` or whatever; but using this as a very roundabout way to get waivers / exceptions is pretty painful. 

See #3845

2019-06-12 01:11 UTC, kekaichinose commented
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

2019-06-12 01:11 UTC, closed without merging