Core Telemetry Interface
inspec/inspec pull request #3903
Opened 2019-03-22 17:26 UTC by miah

Adds a core telemetry interface to InSpec.

Collects local details about Ruby Environment
Collects details about the number of profiles, controls, and tests.
Collects details about the unique types of tests and their average run time.
Can generate a simple report (that is not written anywhere just yet).

ref: https://github.com/inspec/inspec/issues/3846

2019-03-23 12:42 UTC, aaronlippold commented
I think one thing we should add in here is if there are any exceptions raised during the run of any of the profiles and a reference to their data. Right now I'm parsing this out from the results itself but I think this is not more correct home for that data.

2019-03-23 12:46 UTC, aaronlippold commented
Also, if you look here in the `summery` tool you will see other data that we have found useful to collect that may have a good home in telemetry. The other small tool  for parsing the total number of high failed medium passes low skips etc might also be useful as a standard data item but you may or may not agree that it belongs in telemetry. 

https://github.com/mitre/inspec_tools.

2019-03-23 12:50 UTC, aaronlippold commented
I think this was great, along with the Target node asset information like IP + MAC address etc and this data we're really starting to cook with gas :-)

2019-03-25 18:15 UTC, clintoncwolfe requested changes
So, I think this is a great start, but I think it might want to be split up in to several PRs:

 * a base, extremely generic PR that does not know about Reporter Results at all, and only knows how to do generic data series
 * something that knows how to pick apart a ReporterResult and create data series using the generic calls
 * The beginnings of the Config / opt-in system
 * the beginnings of the endpoint system

2019-03-25 18:15 UTC, clintoncwolfe commented on test/unit/utils/telemetry/data_series_test.rb
> +    assert_equal Inspec::Telemetry::DataSeries, @data_series.class
Consider using assert_kind_of for a clearer message on failure

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/utils/telemetry/data_series.rb
> +      @enable = true
Consider naming this `@enabled`

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/utils/telemetry/data_series.rb
> +    attr_accessor :resource, :type, :run_time, :controls, :tests
Design thoughts, here.

As implemented, this DataSeries can only be associated with elements from an InSpec Report.  So, adding new types of data to track will be difficult or nonsensical; we can't add elements to the DataSeries that don't appear in a Report.

I would expect DataSeries to be a container that might have attributes:
 * name
 * data (an Array or similar, of plain data, like strings or integers)
Behavior would include:
 * push or `:<<`, some way of appending to its internal data structure
 * to_json, to_h or other marshalling

During the run, you might collect data series from all sorts of places.
 * there be a data series that tracks a list of resource names used (name: resources/names)
 * a data series that counts deprecations touched (name: deprecations/count, Integer)
 
Point being, don't tie the data representation to *what is in the report*.  At this stage the Telemetry system should be very, very generic, and need not be able to process a report at all.

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/utils/telemetry/config.rb
> +    def initialize
Looks like this class doesn't do anything yet, and presumably isn't used by anything either. Consider removing this file from the PR, then having a tightly-focused PR that includes the config system along with whatever needs it (presumably opt-in).

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/runner_rspec.rb
> +      Inspec.telemetry_report(@formatter.results)
Consider renaming this, perhaps to 
`InSpec::Telemetry.process_reporter_results`.  It's a more awkward name, but it should only be called exactly once - here in the runner.

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/utils/telemetry/global_method.rb
> +  def self.telemetry_report(report)
I suggest not making this a global method (instead a singleton class method, or similar). It will only be called once, so no need to make it easy to get to (and it's maybe not worth "polluting" the `Inspec.*` space).

From my perspective, there is a greater need for a very general global method, something like:

`Inspec.telemetry(:some_data_series_name, value_to_record)`

Its implementation might:
 * Locate the Telemetry collector instance 
 * look up or create a data series
 * append the data point to the data series

It has no opinion on the name of data series, or on the values passed.

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/utils/telemetry/endpoint/file.rb
> +module Inspec::Telemetry::Endpoint
As this is nearly empty, and other endpoint files are empty, I might suggest removing them from this PR, and having a subsequent PR which implements adding a file output, then a later PR which adds an HTTP output, etc.

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/utils/telemetry.rb
> +    def deprecation_add(deprecation)
I actually think Telemetry should not know about deprecations (or possibly even Reporter Results!) at all.

If Telemetry offers a generic way to record data points from anywhere in the codebase, then if the Deprecation system cares about participating in telemetry, it can call the generic data collector from the Deprecation code.

This allows us to add telemetry collection points *anywhere*.

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/utils/telemetry.rb
> +    def data_series
Unless you're doing something special, I think this method should probably go away. Just call the constructor where you need it.

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/utils/telemetry.rb
> +    # @return [TrueClass]
Does this return TrueClass?  I thought it would return the array.

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/utils/telemetry/report.rb
> +  class Report
I think we should find a new name for this. Telemetry has to deliver its results, and the Runner has results, both are called Report or Reporter or `report` methods.

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/utils/telemetry/report.rb
> +    def generate
I think this should be very generic.  Loop over the list of data series, ask them to marshall themselves, assemble in a structure, then (in future PR) send that structure to an endpoint(s).

In other words, this should not know about things like profiles, controls, etc - if it does, we have to change this every time we add or remove a data series.  Plugins might load that want to define data series, or might not be loaded - this would have to have conditionals for lots of things.

2019-03-25 18:15 UTC, clintoncwolfe commented on lib/inspec/utils/telemetry/report.rb
> +    def count_collection_type(collection_type)
I agree we'll have to have some sort of summarization facility... counting is on obvious case. Might want to be thinking about what else.

2019-03-25 18:37 UTC, clintoncwolfe commented
@aaronlippold, a good place to collect ideas for Telemetry would be on #3846 . Anything mentioned here will live and die with this specific PR :-)

2019-04-23 00:37 UTC, closed without merging