Bump website from 3.0 to 4.
inspec/inspec pull request #4022
Opened 2019-05-03 18:51 UTC by zenspider

Specifically using "4" so we don't have to bump on every minor
release.

I mish-mashed the bullet points from 2 different sources. It is
probably wrong or confusing and I'd like extra scrutiny there.

I don't remember slim AT ALL and probably got some stuff wrong.

This should fix #4020.

Signed-off-by: Ryan Davis <zenspider@chef.io>

2019-05-03 19:13 UTC, clintoncwolfe requested changes
Just some minor wording changes, related to changelog

2019-05-03 19:13 UTC, clintoncwolfe commented on www/source/index.html.slim
> +      p.large-11.medium-11 Numerous bugfixes and new features.
"Inputs system overhaul, updated AWS-SDK to v3, support for the new Chef License, and many bugfixes and minor features"

2019-05-03 19:13 UTC, clintoncwolfe commented on www/source/index.html.slim
> +            p Added license acceptance (see below)
p Inputs system overhaul - more consistent, extensible, and predictable
p Updated AWS-SDK to v3
p Laying the foundation for opt-in telemetry
p Support for the new Chef License
p Add support for `more_permissive_than?` on the File resource
p many other minor bugfixes!

2019-05-03 19:13 UTC, clintoncwolfe commented on www/source/index.html.slim
> +            p This release is the first to require accepting a license before using it.
...using it as an executable.

2019-05-03 21:38 UTC, zenspider commented on www/source/index.html.slim
> +            p This release is the first to require accepting a license before using it.
done done and done

2019-05-06 19:46 UTC, clintoncwolfe approved these changes
Thanks!

2019-05-06 21:05 UTC, miah approved these changes

2019-05-07 14:17 UTC, mjingle commented on www/source/index.html.slim
> +            p many other minor bugfixes!
```suggestion
            p Many other minor bugfixes!
```

2019-05-07 14:17 UTC, mjingle commented on www/source/index.html.slim
> +            p Moved the `inspec` executable to a separate gem, `inspec-bin`.  This allows use of the `inspec` gem as a library without the licensing restrictions placed on the executable.
```suggestion
            p Moved the `inspec` executable to a separate gem, `inspec-bin`. This allows the use of the `inspec` gem as a library without the licensing restrictions placed on the executable.
```

2019-05-07 15:25 UTC, mjingle commented
Just a few copyedits and then it looks good to go!

2019-05-07 19:17 UTC, zenspider commented
Thank you @clintoncwolfe and @mjingle! Applied and awaiting CI.

2019-05-07 19:36 UTC, mjingle commented
Ack, committing suggestions via comments does not allow for a DCO to be applied in the process. 👎

2019-05-07 20:23 UTC, clintoncwolfe commented
As this is a website change, I'm going to ignore the CI failures.

2019-05-07 20:23 UTC, merged