Fix github url regex. Add period for repo
inspec/inspec pull request #4089
Opened 2019-05-17 06:12 UTC by mirskiy

For url transforming, the github url regex didn't allow periods in the repo name. Github allows periods in the repo name.

## Description

I allowed periods in the repo in the github url regex.

## Related Issue

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
Thanks!

2019-05-17 06:46 UTC, miah requested changes
Thanks @mirskiy. Could you also add it to the tree regex?

2019-05-17 06:46 UTC, miah commented on lib/fetchers/url.rb
>      GITHUB_URL_WITH_TREE_REGEX = %r{^https?://(www\.)?github\.com/(?<user>[\w-]+)/(?<repo>[\w-]+)/tree/(?<commit>[\w\.]+)(/)?$}
I think we'd need it here too.

2019-05-17 08:46 UTC, zenspider requested changes

2019-05-17 08:46 UTC, zenspider commented on lib/fetchers/url.rb
>      GITHUB_URL_WITH_TREE_REGEX = %r{^https?://(www\.)?github\.com/(?<user>[\w-]+)/(?<repo>[\w-]+)/tree/(?<commit>[\w\.]+)(/)?$}
agreed. good catch.

2019-05-17 08:46 UTC, zenspider commented on lib/fetchers/url.rb
> +    GITHUB_URL_REGEX = %r{^https?://(www\.)?github\.com/(?<user>[\w-]+)/(?<repo>[\w.-]+)(\.git)?(/)?$}
good catch! I totally have repos with periods in their names!

2019-05-17 22:52 UTC, mirskiy commented on lib/fetchers/url.rb
>      GITHUB_URL_WITH_TREE_REGEX = %r{^https?://(www\.)?github\.com/(?<user>[\w-]+)/(?<repo>[\w-]+)/tree/(?<commit>[\w\.]+)(/)?$}
Added to GITHUB_URL_WITH_TREE_REGEX.

2019-05-18 18:28 UTC, mirskiy commented
I updated the tree regex. I also changed the github url regex to be non-greedy for the repo - because we allow periods, it was capturing the ".git" in some of the test cases as part of the repo name (ex. github.com/inspec/inspec.git had repo as inspec.git). Those test cases are now passing.

I rebased against master and it looks like all the test cases are passing when I run locally, but I don't understand AppVeyor and Coveralls so let me know what I need to do to pass those.

2019-05-19 01:26 UTC, miah approved these changes
Thanks @mirskiy, dont worry about appveyor or coveralls at the moment. We're still straightening some things out with them =)

2019-05-19 04:08 UTC, zenspider approved these changes
Great. Thank you!

2019-05-21 18:04 UTC, mirskiy commented
@miah Is there anything else needed to merge this? Thanks!

2019-05-21 19:45 UTC, merged