Switch to 4-stable and add maintainer branches.
inspec/inspec pull request #4184
Opened 2019-06-05 00:44 UTC by zenspider

Signed-off-by: Ryan Davis <zenspider@chef.io>

2019-06-05 04:21 UTC, miah approved these changes

2019-06-05 13:40 UTC, clintoncwolfe requested changes
AFAIK this isn't the branch pattern used on other Chef projects, and will likely lead to confusion when other teams (like releng) work with our codebase. I'd like to hear more discussion about this.

2019-06-05 20:01 UTC, zenspider commented
What type of confusion are you anticipating?

2019-06-05 20:37 UTC, clintoncwolfe commented
As mentioned in a zoom call, I was confused - the 4-stable branch was spurious. As for setting up CI for personal branches prior to PR, I have no objections.

2019-06-06 15:29 UTC, clintoncwolfe approved these changes

2019-06-06 18:33 UTC, merged