Fixed file resource raising UndefinedMethod on source_path
inspec/inspec pull request #4214
Opened 2019-06-18 02:07 UTC by zenspider

This is a first pass at fixing the failure found by @scottvidmar where
file resource was raising undefined_method on nil. The problem was
that the initialize method for file was not being called at all
because Resource#initialize was returning early without reporting
anything.

This fix causes a failure in test/functional/inspec_exec_test.rb where
it is testing a similar scenario but for some reason the unsupported
resources get reported. We need to figure that part out, but in the
meantime this will at least report an error at the root cause rather
than down the road.

Fixes #4208

Signed-off-by: Ryan Davis <zenspider@chef.io>

## Description

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

2019-06-18 02:11 UTC, jerryaldrichiii reviewed
This looks great! Is this a WIP PR and we plan on adding tests for this specific use case? (e.g. a functional test of using aws target with a linux profile)?

2019-06-18 02:12 UTC, zenspider commented
It is a WIP as far as I'm concerned because of the failing test. I don't know if the current failing test has overlap into this space or somehow they avoided each other somehow.

2019-06-18 02:16 UTC, jerryaldrichiii approved these changes
Approving the implementation as it exists now, pending tests.

Thanks for this. Not presenting the user with NoMethodError is valuable in its own right.

2019-06-18 02:45 UTC, zenspider commented
I should have shown what it now does:

```
8422 % ./run.sh exec repro.rb -t aws://
Unsupported resource/backend combination: file / aws. Exiting.
```

2019-06-18 02:48 UTC, zenspider commented
I should also say: #4211 would have saved us some serious time here because of the amount of indirectness the metaprogramming causes.

2019-06-18 06:05 UTC, jerryaldrichiii commented
Tangentially, this may also close https://github.com/inspec/inspec/issues/4048

2019-06-18 15:20 UTC, clintoncwolfe approved these changes
A minor request to fix a comment, but otherwise fine. Thanks!

2019-06-18 15:20 UTC, clintoncwolfe commented on lib/inspec/plugin/v1/plugin_types/resource.rb
> +          # raise if we are supported, or for tests
I think the comment contradicts the code, here. (I think the original did too)

2019-06-18 18:42 UTC, zenspider commented
@clintoncwolfe I don't think this is the right fix. It does address the undefined method error bubbling up (because it was bypassing the `super` call to `initialize`) but it totally breaks ... wait.  WTF? why/how did travis pass? That should NOT be the case as far as I'm concerned. Here is what I see if I run this  file by itself or this one test by itself:

```
  1) Failure:
inspec exec::with a profile that contains skipped resources#test_0001_exits with an error [/Users/ryan/Work/git/inspec/inspec/test/functional/inspec_exec_test.rb:221]:
Expected "[2019-06-17T19:49:21-07:00] WARN: DEPRECATION: AWS resources shipped with core InSpec are being to moved to a resource pack for faster iteration. Please update your profiles to depend on git@github.com:inspec/inspec-aws.git . Resource 'aws_iam_users' (used at /Users/ryan/Work/git/inspec/inspec/test/unit/mock/profiles/aws-profile/controls/aws.rb:3)\n[2019-06-17T19:49:21-07:00] WARN: DEPRECATION: AWS resources shipped with core InSpec are being to moved to a resource pack for faster iteration. Please update your profiles to depend on git@github.com:inspec/inspec-aws.git . Resource 'aws_iam_access_keys' (used at /Users/ryan/Work/git/inspec/inspec/test/unit/mock/profiles/aws-profile/controls/aws.rb:10)\n[2019-06-17T19:49:21-07:00] WARN: DEPRECATION: AWS resources shipped with core InSpec are being to moved to a resource pack for faster iteration. Please update your profiles to depend on git@github.com:inspec/inspec-aws.git . Resource 'aws_s3_bucket' (used at /Users/ryan/Work/git/inspec/inspec/test/unit/mock/profiles/aws-profile/controls/aws.rb:17)\n\nProfile: aws example profile (aws)\nVersion: 1.0.0\nTarget:  local://\n\n\e[38;5;9m  ×  Users that have a password but do not have MFA enabled: /Users/ryan/Work/git/inspec/inspec/test/unit/mock/profiles/aws-profile/controls/aws.rb:1\e[0m\n\e[38;5;9m     ×  Control Source Code Error /Users/ryan/Work/git/inspec/inspec/test/unit/mock/profiles/aws-profile/controls/aws.rb:1 \n     undefined method `aws_client' for #<Train::Transports::Local::Connection:0x00007fdaee127200>\e[0m\n\e[38;5;9m  ×  Do not allow access keys older than 90 days: /Users/ryan/Work/git/inspec/inspec/test/unit/mock/profiles/aws-profile/controls/aws.rb:8\e[0m\n\e[38;5;9m     ×  Control Source Code Error /Users/ryan/Work/git/inspec/inspec/test/unit/mock/profiles/aws-profile/controls/aws.rb:8 \n     undefined method `aws_client' for #<Train::Transports::Local::Connection:0x00007fdaee127200>\e[0m\n\e[38;5;9m  ×  Check our demo bucket for dangerous settings: /Users/ryan/Work/git/inspec/inspec/test/unit/mock/profiles/aws-profile/controls/aws.rb:15\e[0m\n\e[38;5;9m     ×  Control Source Code Error /Users/ryan/Work/git/inspec/inspec/test/unit/mock/profiles/aws-profile/controls/aws.rb:15 \n     undefined method `aws_client' for #<Train::Transports::Local::Connection:0x00007fdaee127200>\e[0m\n\n\nProfile Summary: 0 successful controls, \e[38;5;9m3 control failures\e[0m, 0 controls skipped\nTest Summary: 0 successful, \e[38;5;9m3 failures\e[0m, 0 skipped\n" to include "Resource `aws_iam_users` is not supported on platform".
```

Basically, my `ArgumentError` prevents those other exceptions from being aggregated as test results.

2019-06-18 19:14 UTC, zenspider commented
Here's what I'm doing:

```
m test/functional/inspec_exec_test.rb:221 | ruby -pe 'gsub(/\\n/, "\n")'
```

2019-06-19 17:11 UTC, clintoncwolfe commented on lib/inspec/plugin/v1/plugin_types/resource.rb
> +            raise ArgumentError, msg
Here's an idea, which would at least improve messaging - create a custom exception class (or we may have a suitable one already - see lib/exceptions or lib/errors, I know we have two). Perhaps ResourceUnsupportedError? Then add a `rescue` matching that new exception class in the control evaluator - https://github.com/inspec/inspec/blob/954e6c0ff98113ed41e95b50f5a6651a30572c8c/lib/inspec/rule.rb#L54 . It make a special case of this, but would give you the chance to handle the outcome with a little more finesse.

2019-06-20 18:36 UTC, miah requested changes
Lets pair on this, I think we should try to bubble this up through another exception. If we can't this is fine for now, but we should file a issue to revisit this exit path in the future.

2019-06-20 18:40 UTC, zenspider commented
happy to later today

2019-08-30 20:19 UTC, merged