[WIP] Relative Path Support for the Git Fetcher
inspec/inspec pull request #4217
Opened 2019-06-18 23:05 UTC by clintoncwolfe

## Description

This is an adoption of #3522. Main changes in the adoption were to convert the functional tests to use a fixture-based approach (instead of generating the git repos and profiles each time) and expansion of the tests.

WORK IN PROGRESS: there is a bug in interactions with the cache which I am currently looking at.

OF NOTE: This change requires testing against at least one local git repo. Here, this was handled by creating local git repos, then renaming the .git directory to git-fixture, creating a setup task to make and teardown a symlink, and finally I deleted all the sample hooks. One could imagine other ways of doing that.

NOTE ON PR SIZE: The vast majority of this is just test fixture code. 

Original PR below:
---

This adds support for specifying a path to a profile in a Git repo.

For example, you could have a Git repo containing multiple profiles and you want to specify a single one like below:

```yaml
depends:
  - name: profile-1
    git: https://github.com/myorg/all-my-profiles.git
    relative_path: profiles/my-specific-profile-1
  - name: profile-2
    git: https://github.com/myorg/all-my-profiles.git
    relative_path: profiles/my-specific-profile-2
```

This closes #2167 
This closes #1974 
This closes #1237

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

2019-06-20 19:05 UTC, zenspider requested changes
Minor requests, mostly typos.

2019-06-20 19:05 UTC, zenspider commented on lib/fetchers/git.rb
> +              # This is acourtesy, assuming we're writing to the cache; if we're
`s/acourtesy/a courtesy/`

2019-06-20 19:05 UTC, zenspider commented on lib/fetchers/git.rb
> +              # vendoring to somthing more complex, don't bother.
`s/somthing/something/`

2019-06-20 19:05 UTC, zenspider commented on test/functional/git_fetcher_test.rb
> +      assert_exit_code(1, run_result) # General user error
Please no more testing exit code before output. It is the least amount of usable information when things go wrong.

2019-06-20 19:05 UTC, zenspider commented on lib/fetchers/git.rb
> +            FileUtils.cp_r(working_dir + "/.", destination_path)
Just curious, but why is "/." being tacked on? Can `working_dir` be... a symlink? Wouldn't that be resolved?

2019-06-20 19:05 UTC, zenspider commented on lib/fetchers/git.rb
> +                                      "within profile in git repo specified by '#{@remote_url}'")
```ruby
raise ArgumentError, "msg"
```

2019-06-20 19:05 UTC, zenspider commented on test/functional/git_fetcher_test.rb
> +  end
nice

2019-06-21 02:10 UTC, clintoncwolfe commented on lib/fetchers/git.rb
> +            FileUtils.cp_r(working_dir + "/.", destination_path)
I could not really say; that was in existing code, and my only changes were to clarify the variable names. I would note that `working_dir + '/', destination_path` carries a different meaning, and would copy working_dir itself, not the things in it which is what is intended. Anyway, it does continue to work.

working_dir won't be a symlink; it's the result of a `Dir.mktmpdir` block.

2019-07-02 21:14 UTC, zenspider approved these changes

2019-07-12 17:47 UTC, miah approved these changes

2019-07-30 18:37 UTC, merged