Updating Maintainers
inspec/inspec pull request #4287
Opened 2019-07-11 01:09 UTC by kekaichinose

Signed-off-by: Keka Ichinose <rikoomi@hotmail.com>

## Description

Updating maintainers to reflect the current team members

## Related Issue

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

2019-07-11 17:52 UTC, miah approved these changes
Thanks @kekaichinose ! =)

2019-07-15 17:04 UTC, clintoncwolfe requested changes
Looks like Ryan's username is wrong otherwise looks good!

2019-07-15 17:04 UTC, clintoncwolfe commented on MAINTAINERS.toml
> +          "zenspyder"
Ryan's username is zenspider, not zenspyder

2019-07-15 17:04 UTC, clintoncwolfe commented on MAINTAINERS.toml
> +    GitHub = "zenspyder"
Ryan's username correction here, too

2019-07-15 17:14 UTC, clintoncwolfe approved these changes
Thanks, looks great!

2019-07-15 17:19 UTC, merged