Fixed typo in umask example
inspec/inspec pull request #4360
Opened 2019-08-04 16:09 UTC by kclinden

changed login_def to login_defs

## Description
Example has a typo that breaks the test. 

## Related Issue
N/A

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ x ] I have read the **CONTRIBUTING** document.

2019-08-06 23:23 UTC, zenspider approved these changes
Good catch! Thank you!

2019-08-06 23:23 UTC, zenspider requested changes
Oops! But we do need a DCO tag on your commit!

2019-08-07 17:35 UTC, miah approved these changes
Thanks @kclinden

2019-08-07 17:37 UTC, miah commented
This probably falls under the Obvious Fix policy.

https://github.com/inspec/inspec/blob/master/CONTRIBUTING.md#obvious-fix-policy

But your commit doesn't note this, and there is no DCO. @kclinden can you just reply to this with something along the lines of 'this was a obvious fix' and i'll merge. (or update/add a DCO to your commit)

Thanks =)

2019-08-07 17:46 UTC, kclinden commented
------------------------------------------------------------------------
commit 34275b8c1178a9e8e6f8526e3682fc500c62f121
Author: Kasey Linden
Date:   Mon Aug 4 2019 

  Fix typo in the login_defs example

  Obvious fix.

------------------------------------------------------------------------

> commit doesn't note this, and there is no DCO. @kclinden can you just reply to this with

2019-08-08 17:13 UTC, clintoncwolfe commented
Thanks!

2019-08-08 17:13 UTC, merged