Do not call return inside of an initialize method.
inspec/inspec pull request #4366
Opened 2019-08-06 23:17 UTC by zenspider

It does NOT do what you think it does. It does NOT prevent an object
from coming back. All it does is have an uninitialized (or partially
initialized) object come back, which isn't helpful.

Signed-off-by: Ryan Davis <zenspider@chef.io>

2019-08-06 23:20 UTC, miah approved these changes

2019-08-06 23:21 UTC, miah approved these changes
I wonder about side effects on this one though

2019-08-07 15:19 UTC, clintoncwolfe requested changes
I think it's actually intentional behavior with a bad comment - the intent really is not to affect the return value, but to just avoid further initializiation.

If that entire initialization block that follows were placed under an `unless`, that might be clearer, and not involve a suspicious return-from-initialize...

```
# Stop initializing if we are on an unsupported or test backend
unless supported || test_backend
  begin
    super(*args)
  rescue...
    ...
  end
end
```

2019-08-07 15:19 UTC, clintoncwolfe requested changes
(double commented, whoops)

2019-08-07 20:43 UTC, zenspider commented
It might be confusingly named, but Initialization _needs_ to complete for our resources to work correctly. Simple examples are `def to_s` using ivars to generate a string.

2019-08-08 15:04 UTC, clintoncwolfe approved these changes
If that's the intent - to always initialize resources - I'll accept, and I've updated the PR title for you to reflect the intent.

2019-08-19 16:55 UTC, merged