Add startuser systemd service
inspec/inspec pull request #4367
Opened 2019-08-07 04:07 UTC by mbaitelman

Add a check to see which user a systemd resource is running under

Depends on #4363

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:
- [X] I have read the **CONTRIBUTING** document.

2019-08-07 17:46 UTC, miah approved these changes
Thanks @mbaitelman

2019-08-07 17:47 UTC, miah requested changes
Looks like we've got some test issues to address before this can be merged.

2019-08-07 17:49 UTC, miah commented
Did you intend to include the windows changes here too or only in https://github.com/inspec/inspec/pull/4363 ? Looks like this PR might need a bit more cleanup.

2019-08-07 22:22 UTC, mbaitelman commented
@miah It was built on the windows resource update mainly as a proof of concept for building on top of resources. 
If there is an interest in this Ill work on fixing it. 
(From all the checks I did on my machines nothing runs on a specific user)

2019-09-23 18:29 UTC, clintoncwolfe commented
@mbaitelman Are you interested in continuing this? If so, it looks like there is a failing test. Please correct the test and then we can continue review; otherwise we'll need to close this as an abandoned PR in a few days.

2019-09-25 06:03 UTC, mbaitelman commented
Moved to #4516

2019-09-25 06:03 UTC, closed without merging