Fixed MssqlSession.query not escaping double quote correctly
inspec/inspec pull request #4393
Opened 2019-08-15 10:35 UTC by dalee-bis

## Description

When `MssqlSession.query` is escaping the `"` character, it is doing so by prefixing it with a backslash (e.g. `\"`). This does not escape the quote character. It should be escaped by adding an additional double quote character (e.g. `""`).

## Related Issue

https://github.com/inspec/inspec/issues/4392

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

2019-08-17 18:10 UTC, miah requested changes
Thanks for the find and contribution @dalee-bis! Could you add a test for this? The test file is here: https://github.com/inspec/inspec/blob/master/test/unit/resources/mssql_session_test.rb#L65

Your commit will also need at DCO signature: https://github.com/inspec/inspec/blob/master/CONTRIBUTING.md#dco-sign-off-methods

2019-08-19 15:20 UTC, dalee-bis commented
Sorry but I'm not very familiar with Ruby. I only managed this change because it was mostly regex and easily testable at https://www.tutorialspoint.com/execute_ruby_online.php. I don't have an environment set up to ensure the test is running successfully.

Also editing the commit message is causing issues due to the privacy settings on my account. Is the DCO required for a 3 character change?

2019-08-19 22:40 UTC, miah approved these changes
You're right, this likely falls under our Obvious Fix policy so we can skip DCO.

2019-08-19 22:48 UTC, zenspider approved these changes

2019-08-19 22:48 UTC, zenspider commented on lib/inspec/resources/mssql_session.rb
> +      escaped_query = q.gsub(/\\/, '\\\\').gsub(/"/, '""').gsub(/\$/, '\\$')
I believe this is right for SQL... but this type of change _should_ have a test behind it if at all possible. I just saw your comment about your ruby experience so I'm gonna approve and try to follow up on this with the test (or at least file an issue for it).

2019-09-23 16:43 UTC, merged