Fixed multiline error described in issue #3921
inspec/inspec pull request #4400
Opened 2019-08-20 10:10 UTC by Axuba

## Description

Addresses the bug that happens on RedHat 5 and 6 that if a filesystem has a long name, it puts a newline right after the filesystem name, and InSpec's describe filesystem doesn't manage it. Adding a 'P' at the df command addresses this issue

## Related Issue

Addresses issue [#3921 ](https://github.com/inspec/inspec/issues/3921)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.

2019-08-20 19:39 UTC, clintoncwolfe reviewed
So on #3921, there is a suggestion to add -P at https://github.com/inspec/inspec/blob/29bec90b1b487ab33b10988a9513c94b4b2b0a3e/lib/resources/filesystem.rb#L95 - which we noticed you did on an early commit, then rolled back. What obstacle did you encounter, and why does string manipulation of the output seem better? Thanks!

2019-08-20 19:45 UTC, zenspider requested changes
Thank you for your PR!

I have the same question about `-P`, but would also like to see this PR rewritten to be a single commit. I usually do that with `git rebase -i <sha of start>` (via emacs' magit, which makes it a breeze), but you can also roll out all the commits (eg `git reset HEAD^` * N commits) and add a new commit w/ a final message (plus DCO please)... or start a new PR and just patch the current diff in. If anything, there are too many ways to do this.

2019-08-20 19:47 UTC, Axuba commented
> So on #3921, there is a suggestion to add -P at
> 
> https://github.com/inspec/inspec/blob/29bec90b1b487ab33b10988a9513c94b4b2b0a3e/lib/resources/filesystem.rb#L95
> - which we noticed you did on an early commit, then rolled back. What obstacle did you encounter, and why does string manipulation of the output seem better? Thanks!

@clintoncwolfe Hello, before committing the changes I tested it locally in my RHEL6 & RHEL7 servers, and it worked perfectly and it fixed the issue on RHEL6, while still working on RHEL7. But when I committed I noticed that the inspec-master-verify failed as you can see [here](https://buildkite.com/chef-oss/inspec-inspec-master-verify/builds/343). I wasn't sure why would it work on RedHat machines but I neither knew the environment those tests are run to.

So I basically tried to fix the issue doing a work-around, since I don't know the enviromnent those tests use, that manages to fix the issue on RedHat 6&7 servers while passing the verifier. And I came with the substitution String.

@zenspider thanks for the tips, it's the first time I do this, I do it as soon as I can :)

2019-08-20 20:48 UTC, Axuba commented
Sorry I had some problems with the branch. @zenspider Everything is in 1 commit now.

2019-10-24 04:52 UTC, miah commented
Thanks for the work on this @Axuba, decided on a slightly different fix in #4637

2019-10-24 04:52 UTC, closed without merging