Fix config clearing
inspec/inspec pull request #4483
Opened 2019-09-12 18:33 UTC by frezbo

Fixes #4481

2019-09-12 21:26 UTC, miah requested changes
Could you take a look at the tests?

2019-09-12 23:20 UTC, clintoncwolfe requested changes
Thanks for this - I think it's a great idea. I'm OK with adding a reset functionality to Inspec::Config, but I think using it should be at-will - just because you call the Runner.run doesn't mean the config should get reset.

2019-09-12 23:20 UTC, clintoncwolfe commented on lib/inspec/runner.rb
> +      Inspec::Config.__reset
I disagree with adding this line here.  I think if you are a consumer of `Inspec::Runner`, you can call `Inspec::Config.__reset` yourself after calling `run`. I'm not sure it makes sense to always reset the config.

2019-09-13 04:48 UTC, frezbo commented on lib/inspec/runner.rb
> +      Inspec::Config.__reset
yes I agree with you. I don't think kitchen-inspec needs these changes as it will always run one profile at a time I guess.

2019-09-13 19:11 UTC, clintoncwolfe approved these changes
Ok, with just an addition of a reset to Config, and no obligatory call to it, I think this is a fine addition - many thanks!

2019-09-30 22:43 UTC, zenspider commented on lib/inspec/runner.rb
> +      Inspec::Config.__reset
Agreed. But looks resolved.

2019-09-30 22:43 UTC, zenspider approved these changes

2019-09-30 22:43 UTC, miah approved these changes

2019-09-30 22:43 UTC, merged