Split out Inspec::Input functional code from the code generation code.
inspec/inspec pull request #4485
Opened 2019-09-13 04:13 UTC by zenspider

Includes moving errors into Inspec::Input and Inspec::InputRegistry.

Fixes #4456.
Fixes #4473.

Signed-off-by: Ryan Davis <zenspider@chef.io>

2019-09-13 17:14 UTC, miah requested changes
`File does not exist: inspec/input`

2019-09-13 20:27 UTC, zenspider commented
I R DUM

2019-09-16 21:56 UTC, clintoncwolfe approved these changes
Thanks, a clean move!

2019-09-17 00:03 UTC, miah approved these changes

2019-09-17 00:03 UTC, merged