Goodbye Gordon!
inspec/inspec pull request #4577
Opened 2019-10-09 07:21 UTC by miah

![](https://media.giphy.com/media/hRhCc5bbYh9w4/giphy.gif)

Fixes 4301

2019-10-09 07:35 UTC, miah commented
![](https://media.giphy.com/media/rZ2B5iCm0dCp2/giphy.gif)

2019-10-16 18:12 UTC, zenspider commented
How in the hell does a "simple rename" hit 41 files and 9 commits?!?! Can we file some extra issues off of the lessons learned here? Clearly there's some fragility showing. Probably also some bad design or test assumptions as well.

2019-10-17 00:15 UTC, zenspider requested changes
minor changes requested. Looks good (tho expansive) otherwise.

Please file issues for any "lessons learned" while digging into this.

2019-10-17 00:15 UTC, zenspider commented on examples/profile/controls/example.rb
> +  ref 'Example Requirements 1.0', uri: 'http://...'
It's easier to track this stuff if you have a commit for JUST renames and then do content changes after.

2019-10-17 00:15 UTC, zenspider commented on test/functional/inspec_exec_json_test.rb
> +        .find { |x| p x; x["id"] =~ /generated from example/ }["id"]
This looks like my junk left in.

2019-10-17 00:15 UTC, zenspider commented on test/functional/inspec_exec_json_test.rb
> +        .find { |x| x["id"] =~ /generated from example/ }["id"]
this is a perfect case for `git absorb`!!!

2019-10-17 00:15 UTC, zenspider commented on test/functional/helper.rb
> +        warn "XIT: %p"              % [run_result.exit_status]
yessss... so much better when something goes wrong!

2019-10-17 00:15 UTC, zenspider commented on test/functional/inspec_exec_json_test.rb
> +
Prolly should remove... only needed while debugging. Slower otherwise (tho... only on failures).

2019-10-17 00:15 UTC, zenspider commented on test/functional/inspec_exec_json_test.rb
> -        "sha256" => "de67a044d7be7090982740755ff582af1cefaf37261c5adda57b9502ffefc973",
YES

2019-10-17 00:16 UTC, miah commented on test/functional/inspec_exec_json_test.rb
> +        .find { |x| p x; x["id"] =~ /generated from example/ }["id"]
Ya I already removed that.

2019-10-17 18:53 UTC, clintoncwolfe approved these changes
Thank you - this has been much overdue!

2019-10-17 18:53 UTC, clintoncwolfe commented on examples/profile/controls/example-tmp.rb
> +describe file('/tmp') do
Thank you for re-ordering that to have the plain test after the control.

2019-10-17 19:26 UTC, zenspider approved these changes

2019-10-17 19:38 UTC, merged