Make input() work in describe.one
inspec/inspec pull request #4666
Opened 2019-11-04 15:36 UTC by clintoncwolfe

## Description

Adds the ability for `input()` (and its non-evaluating friend `input_object()`) to work inside a `describe.one` block. 

While this was reported as a regression, I don't believe this functionality was ever in place, either as `input()` or as `attribute()` - reproduction steps with a version welcome on #4523.

Reviewer notes:
This PR currently includes a simple functional test.
There is a small amount of code duplication which is noted in a TODO which could be factored out.

## Related Issue

Fixes #4523 
Fixes #3650 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

2019-11-04 21:46 UTC, zenspider approved these changes
Please file issues for todos

2019-11-05 20:06 UTC, miah requested changes
Looks good just one question about `__profile_id`

2019-11-05 20:06 UTC, miah commented on lib/inspec/describe_base.rb
> +    def __profile_id
Is this a private method? Should it be below a `private`?

2019-11-05 21:00 UTC, clintoncwolfe commented on lib/inspec/describe_base.rb
> +    def __profile_id
All of these methods end up exposed as part of the DSL inside `describe.one` blocks, which are executed using `instance_eval` - so while we can make this private, it won't actually make any difference. The double-underscore is there to discourage people from accidentally finding it. 

I'll add an RDoc comment to that effect.

2019-11-06 17:38 UTC, miah commented on lib/inspec/describe_base.rb
> +    def __profile_id
Thanks!

2019-11-06 17:39 UTC, miah commented on lib/inspec/describe_base.rb
> +    # so it is fully visible. The double undersroe is there to discourage
undersCORE. <3

2019-11-06 17:39 UTC, miah approved these changes
Fix typo and this is great. Thanks =)

2019-11-07 16:58 UTC, merged