Remove all deprecated aws and azure resources.
inspec/inspec pull request #4813
Opened 2019-12-30 21:51 UTC by zenspider

These have been available in inspec-aws and inspec-azure for about a
year now.

Signed-off-by: Ryan Davis <zenspider@chef.io>

2019-12-31 16:51 UTC, clintoncwolfe requested changes
This MUST be held until a major version bump, and we haven't discussed the timing or branching strategy for that, AFAIK. There are definitely people in the wild still using the core AWS resources.

Additionally, even if "removed", we'd need to leave behind deprecation stubs for one major version - so if you tried to use a resource that is now gone, you'd get a deprecation notice and further instructions, not an opaque error.

2019-12-31 21:18 UTC, zenspider commented
I don't think it needs to be held at all. We can release these resources as gems and add dependencies to those gems. Once we've made it through a major rev, final removal would involve removing the dependencies for them. This should be doable independent of any resource pack rework we want to do (and if anything should help that effort along).

2020-01-15 20:43 UTC, miah commented
> Additionally, even if "removed", we'd need to leave behind deprecation stubs for one major version - so if you tried to use a resource that is now gone, you'd get a deprecation notice and further instructions, not an opaque error.

https://github.com/inspec/inspec/blob/master/lib/resource_support/aws/aws_resource_mixin.rb#L3

https://github.com/inspec/inspec/blob/master/etc/deprecations.json#L19-L22

#3822

2020-01-22 19:34 UTC, miah approved these changes

2021-03-25 20:15 UTC, closed without merging