issue 4807: shallow copy of params missed inputs
inspec/inspec pull request #4815
Opened 2019-12-31 00:42 UTC by nazliBeit

issue 4807: shallow copy of params missed inputs

## Description
using `dup` to shallow copy `params`, which means `inputs` is not copied into `res` yet and `res[:inputs] = []` branch always executes

## Related Issue
https://github.com/inspec/inspec/issues/4807

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.

2019-12-31 17:56 UTC, clintoncwolfe commented
Hi! Thanks for the contribution! Our project requires a [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco) (DCO) indicating that the code you submit is your own work.  Basically, you just need to do `git commit -s --amend --no-edit` and then `git push -f`; the -s "signs" the commit.

Thanks!

2019-12-31 18:04 UTC, nazliBeit commented
> Hi! Thanks for the contribution! Our project requires a [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco) (DCO) indicating that the code you submit is your own work. Basically, you just need to do `git commit -s --amend --no-edit` and then `git push -f`; the -s "signs" the commit.
> 
> Thanks!

Hi, 
It's done.
Thanks!

2019-12-31 18:08 UTC, clintoncwolfe requested changes
This really needs a test - probably pair in which the profile has no inputs, and one in which it has multiple.  Right now I don't see how this ever worked.... but I"m not sure the change fixes it either.

2019-12-31 18:19 UTC, pakdel commented
> This really needs a test - probably pair in which the profile has no inputs, and one in which it has multiple. Right now I don't see how this ever worked.... but I"m not sure the change fixes it either.

Seems to be working now
```
inspec % bundle exec inspec-bin/bin/inspec exec examples/profile-attribute --reporter json | jq '.profiles[0].attributes'
[2019-12-31T13:16:33-05:00] WARN: Input 'password' does not have a value. Use --input-file to provide a value for 'password' or specify a  value with `attribute('password', value: 'somevalue', ...)`.
[2019-12-31T13:16:33-05:00] WARN: Input 'password' does not have a value. Use --input-file to provide a value for 'password' or specify a  value with `attribute('password', value: 'somevalue', ...)`.
[
  {
    "name": "user",
    "options": {
      "value": "alice"
    }
  },
  {
    "name": "password",
    "options": {
      "value": "Input 'password' does not have a value. Skipping test."
    }
  }
]
inspec % bundle exec inspec-bin/bin/inspec exec examples/profile-attribute --reporter json --input user=bob password=password | jq '.profiles[0].attributes'
[
  {
    "name": "user",
    "options": {
      "value": "bob"
    }
  },
  {
    "name": "password",
    "options": {
      "value": "password"
    }
  }
]
inspec % bundle exec inspec-bin/bin/inspec exec examples/profile-attribute --reporter json --input-file examples/profile-attribute.yml | jq '.profiles[0].attributes'
[
  {
    "name": "user",
    "options": {
      "value": "bob"
    }
  },
  {
    "name": "password",
    "options": {
      "value": "secret"
    }
  }
]
inspec % 
```

2019-12-31 21:22 UTC, pakdel commented
> This really needs a test - probably pair in which the profile has no inputs, and one in which it has multiple. Right now I don't see how this ever worked.... but I"m not sure the change fixes it either.

I think these two tests need to be updated: `test/unit/inputs/input_registry_test.rb` and `test/unit/inputs/input_test.rb`
Am I correct @clintoncwolfe ?

2020-01-01 21:07 UTC, zenspider approved these changes
The windows failures on CI are ignorable. If you update master and rebase against it, they'll go green again... but this is optional.

As far as writing tests for this, yes... those two test files would be the right place for them to go.

I don't think missing tests really need to hold back this PR. It is obvious that this code never worked correctly and we should have already had a test for that. If you want to write them, go for it! But I think this PR is good as it stands.

2020-01-03 16:46 UTC, clintoncwolfe approved these changes

2020-01-03 16:47 UTC, merged

2020-02-03 02:27 UTC, nazliBeit commented
> This really needs a test - probably pair in which the profile has no inputs, and one in which it has multiple. Right now I don't see how this ever worked.... but I"m not sure the change fixes it either.

I added a test: https://github.com/inspec/inspec/pull/4883

2020-02-03 02:29 UTC, nazliBeit commented
> > This really needs a test - probably pair in which the profile has no inputs, and one in which it has multiple. Right now I don't see how this ever worked.... but I"m not sure the change fixes it either.
> 
> I think these two tests need to be updated: `test/unit/inputs/input_registry_test.rb` and `test/unit/inputs/input_test.rb`
> Am I correct @clintoncwolfe ?

I think the test should rather be in the `test/unit/profiles/profile_test.rb`, as it was the profile that was not loading them