Make test-kitchen with Vagrant work
inspec/inspec pull request #4895
Opened 2020-02-07 00:45 UTC by miah

v1 of our TK rework. This starts getting tests running on Vagrant for local testing.

2020-02-07 00:47 UTC, tas50 commented on kitchen.vagrant.yml
> +      box: bento/centos-6
This all comes for free with kitchen-vagrant

2020-02-10 15:03 UTC, clintoncwolfe requested changes
This is awesome! However, looks like we need to build `inspec-core` and then install it as such...

```
       [2020-02-10T15:00:16+00:00] FATAL: Chef::Exceptions::FileNotFound: cookbook_file[/root/inspec.gem] (run-first::default line 1) had an error: Chef::Exceptions::FileNotFound: Cookbook 'run-first' (1.0.0) does not contain a file at any of these locations:
         files/host-resources-core-ubuntu-1804.vagrantup.com/inspec.gem
         files/ubuntu-18.04/inspec.gem
         files/ubuntu/inspec.gem
         files/default/inspec.gem
         files/inspec.gem

       This cookbook _does_ contain: ['files/.gitkeep','files/inspec-core-bin.gem','files/inspec-core.gem']
``` 

Super close!

2020-02-10 18:59 UTC, miah commented
> This is awesome! However, looks like we need to build `inspec-core` and then install it as such...
> 
> ```
>        [2020-02-10T15:00:16+00:00] FATAL: Chef::Exceptions::FileNotFound: cookbook_file[/root/inspec.gem] (run-first::default line 1) had an error: Chef::Exceptions::FileNotFound: Cookbook 'run-first' (1.0.0) does not contain a file at any of these locations:
>          files/host-resources-core-ubuntu-1804.vagrantup.com/inspec.gem
>          files/ubuntu-18.04/inspec.gem
>          files/ubuntu/inspec.gem
>          files/default/inspec.gem
>          files/inspec.gem
> 
>        This cookbook _does_ contain: ['files/.gitkeep','files/inspec-core-bin.gem','files/inspec-core.gem']
> ```
> 
> Super close!

https://github.com/inspec/inspec/pull/4895/files#diff-7390c51a77fd2549a8f2a9412e6d727aR13-R15

2020-02-10 19:32 UTC, miah commented
> This is awesome! However, looks like we need to build `inspec-core` and then install it as such...
> 
> ```
>        [2020-02-10T15:00:16+00:00] FATAL: Chef::Exceptions::FileNotFound: cookbook_file[/root/inspec.gem] (run-first::default line 1) had an error: Chef::Exceptions::FileNotFound: Cookbook 'run-first' (1.0.0) does not contain a file at any of these locations:
>          files/host-resources-core-ubuntu-1804.vagrantup.com/inspec.gem
>          files/ubuntu-18.04/inspec.gem
>          files/ubuntu/inspec.gem
>          files/default/inspec.gem
>          files/inspec.gem
> 
>        This cookbook _does_ contain: ['files/.gitkeep','files/inspec-core-bin.gem','files/inspec-core.gem']
> ```
> 
> Super close!

Yes. I am currently having issues with `chef_gem`  or `execute` installing these together though.

2020-02-12 19:41 UTC, zenspider approved these changes

2020-05-12 16:20 UTC, james-stocks commented
I'd rather not merge this and have it live in Expeditor until we have a current plan to tackle the #4422 epic - we can re-open this PR at that time.

2020-05-12 16:20 UTC, closed without merging