Fix freebsd osfamily user group tests
inspec/inspec pull request #5123
Opened 2020-06-29 12:52 UTC by fzipi

## Description

This PR fixes issues with os family naming. Family is always `bsd`, and if you want to match the name, `os[:name]` should be used.

## Related Issue

#5119 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

2020-07-07 12:54 UTC, fzipi commented
Hey @Schwad ! Can you take a look at this one?

2020-07-14 11:50 UTC, Schwad requested changes
Hello @fzipi ! 👋 

Thanks again for this PR as well! 🙏  Looks clear to me, can I request you update the test at `test/unit/resources/user_test.rb:118` so that this passes the pipeline? https://buildkite.com/chef-oss/inspec-inspec-master-verify/builds/2016#6a14c18f-adbc-4205-ae27-3968d834fc04

I might also ask @james-stocks for his eyes on this when he has the chance as he might have additional context for this that I don't have.

2020-07-16 14:07 UTC, fzipi commented
Hey @Schwad !

Found out that the `id root` fixture was the problem, showing linux values. Now I've added a new user so tests should pass.

2020-07-16 14:17 UTC, Schwad commented
Sweet - thanks @fzipi ! I may be out of office before the pipelines run but will definitely get a look onto this tomorrow -cheers!

2020-07-21 11:25 UTC, fzipi commented
Hey @Schwad ! Any news on this?

2020-07-22 11:16 UTC, Schwad approved these changes

2020-07-22 11:20 UTC, Schwad commented
Hi @fzipi ! Thank you so much for this and looks good to me. I've requested a review as well from @james-stocks to get his eyes on this before merge. 

One final request? Generally we ask that PRs be [squashed into one commit](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) before merge, this makes it easier for us in future when using `git bisect` and also helps us to keep the commit history clear. Thank you! 🙏

2020-07-22 11:44 UTC, fzipi commented
@Schwad Done!

2020-07-24 18:24 UTC, fzipi commented
Sadly I can't see why this one failed. It is working locally.

2020-07-27 17:08 UTC, fzipi commented
@Schwad Do you know why this pipeline is failed? I can't access that one.

2020-07-29 09:12 UTC, merged