Switch to builtin expeditor action for package cache purge
inspec/inspec pull request #5158
Opened 2020-07-21 14:51 UTC by james-stocks

Using our own bash script doesn't seem to be supported anymore.

Signed-off-by: James Stocks <jstocks@chef.io>

2020-07-21 14:56 UTC, tduffield approved these changes

2020-07-21 17:12 UTC, tduffield requested changes

2020-07-21 17:12 UTC, tduffield commented on .expeditor/config.yml
> +    - purge_packages_chef_io_fastly:{{target_channel}}/inspec/latest
so `artifact_published` doesn't have a `target_channel` metadata. This should likely be just `{{channel}}` or hardcoded to `stable`:  https://expeditor-acceptance.chef.io/docs/reference/workloads/#artifact_published

2020-08-27 10:23 UTC, Schwad commented
Aha - this was my fault missing this PR. The change was found (the painful way!) during a followon release and this has now been implemented here: https://github.com/inspec/inspec/commit/f0f7bb99377b3166dc79c3278c9aa0c097ef25c7

Closing this but I should've caught it in the first place!

2020-08-27 10:23 UTC, closed without merging