Remove .0 from macos builder name
inspec/inspec pull request #5413
Opened 2021-02-17 20:21 UTC by clintoncwolfe

Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>

## Description

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

2021-02-17 20:40 UTC, kagarmoe approved these changes

2021-02-19 22:19 UTC, tduffield commented on .expeditor/release.omnibus.yml
>    mac_os_x-10.13-x86_64:
You'll also want to switch your builder from 10.13 to 10.14. We deprecated 10.13 awhile ago.

2021-02-20 00:46 UTC, tduffield requested changes
There is a bug with this logic upstream. Need to sort that out before this is merged.

2021-02-22 13:04 UTC, tduffield commented
@clintoncwolfe I'd like to get the 10.14 builder change out, so we should either open a new PR with just that change, or update this PR to keep the `11.0` and merge it.

2021-02-22 20:49 UTC, clintoncwolfe commented
I've moved the change to 10.14 onto a separate PR, #5415

2021-02-26 21:02 UTC, tduffield approved these changes
Alright, we are ready to merge this :) Thanks for your patience.

2021-03-01 20:54 UTC, merged