Integrate InSpec check with Cookstyle
inspec/inspec pull request #5618
Opened 2021-08-16 10:24 UTC by Nik08

Signed-off-by: Nikita Mathur <nikita.mathur@chef.io>

## Description

InSpec check now also checks for code offenses using `cookstyle` gem.
## Related Issue

Closes #5611 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

2021-08-24 02:31 UTC, clintoncwolfe commented on lib/inspec/cli.rb
> +        ui.plain_line("No errors or warnings or offenses")
"No errors, warnings, or offenses"

2021-08-24 02:32 UTC, clintoncwolfe commented on Gemfile
> +
This should probably be a gemspec dependency, since we want to be able to run inspec check from gem installs.

2021-08-24 02:34 UTC, clintoncwolfe commented on lib/inspec/profile.rb
> +            "--only=InSpec/Deprecations,InSpec/Deprecations/AttributeHelper,InSpec/Deprecations/AttributeDefault",
This line will not age well, as more cops are added. Is there a way to specify "InSpec/*"? @tas50?

2021-08-24 02:37 UTC, clintoncwolfe commented on test/functional/inspec_check_test.rb
> +      _(out.stdout).must_match(/No errors or warnings or offenses/)
"No errors, warnings, or offenses"

2021-08-24 02:38 UTC, clintoncwolfe requested changes
Couple of minor things to change - most important one being we need to call cookstyle without specifying the exact rules, we want all the rules in the InSpec category.

2021-08-24 02:57 UTC, tas50 commented
Sadly right now you can't say --only InSpec. We're the only people doing the 3 level configs and that's a use case they haven't gotten working. It's something we need to track down and fix so people can do the same thing with the Chef cops. What you can do is this though:

`InSpec/Deprecations`, `InSpec/Correctness`, `InSpec/Modernize` `InSpec/RedundantCode`, `InSpec/Style`,  and `InSpec/Sharing`. Those match the categories we have for Chef cops right now and it's pretty future proof.

2021-08-25 10:34 UTC, Nik08 commented
> Couple of minor things to change - most important one being we need to call cookstyle without specifying the exact rules, we want all the rules in the InSpec category.

I have made the minor changes as requested @clintoncwolfe. About not specifying the exact rules, I tried using the cop categories mentioned by @tas50 but since most of those cops definitions do not exist for InSpec right now in cookstyle gem, those were overriding the offenses produced by the one cop which does exist and was returning zero offenses. 

So for now i have only included `InSpec/Deprecations` cop which exists in cookstyle.

2021-09-28 04:53 UTC, clintoncwolfe commented
Before we can merge this, we need to update the CLI docs with an updated description of what `inspec check` does, as its behavior has changed. See https://github.com/inspec/inspec/blob/main/docs-chef-io/content/inspec/cli.md

2021-09-30 21:01 UTC, IanMadd commented on docs-chef-io/content/inspec/cli.md
> +Verify metadata in inspec.yml. Verify control data has fields (title, description, impact) defined and that all controls have visible tests. Verify control is not using deprecated InSpec DSL.
```suggestion
Verify the metadata in the inspec.yml file, verify that control blocks have the correct fields (title, description, impact) defined, that all controls have visible tests, and that controls are not using deprecated InSpec DSL code.
```

2021-10-25 23:32 UTC, merged