Updated the Resource Count of Chef InSpec
inspec/inspec pull request #5700
Opened 2021-10-18 13:05 UTC by dishanktiwari2501

Signed-off-by: Dishank Tiwari <dtiwari@progress.com>

## Description

As new resources are merged this number should get updated. Right now it says 80 when the real number is just shy of 500. It makes the product look bad when we don't talk about its full capabilities.

## Related Issue

https://github.com/chef/chef-web-docs/issues/3392

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

2021-10-19 03:45 UTC, kagarmoe approved these changes

2021-11-12 15:26 UTC, kagarmoe requested changes

2021-11-12 15:26 UTC, kagarmoe commented on docs-chef-io/content/inspec/_index.md
> +Chef InSpec has around 500 [resources](/inspec/resources/) ready use--apache to zfs pool.
```suggestion
Chef InSpec has 500+ [resources](/inspec/resources/) ready use--apache to zfs pool.
```

2021-11-12 15:26 UTC, kagarmoe commented on docs-chef-io/content/inspec/_index.md
> +Chef InSpec has around 500 [resources](/inspec/resources/) ready use--apache to zfs pool.
The command `ls | wc -l` shows 500 files in the docs-chef-io/content/inspec/resources directory. If we use `500+` then we won't need to change it until inspec hits 600 resources.

2021-11-20 06:27 UTC, clintoncwolfe commented
#5639 also updated the resource count and has already been merged - I'm going to close this one as a duplicate.

2021-11-20 06:27 UTC, closed without merging