CHEF-65: Switch inspec-6 to be the main branch
inspec/inspec pull request #6591
Opened 2023-08-09 09:07 UTC by Vasu1105

## Description

This is to update the expeditor configuration to get ready for InSpec 6 release.

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

2023-08-15 19:25 UTC, clintoncwolfe requested changes

2023-08-15 19:25 UTC, clintoncwolfe commented on .expeditor/config.yml
> -  - inspec-6:
At this time, we should not delete the inspec-6 release branch from the configuration. We want to leave it untouched, matching version 6.* .

2023-08-15 19:25 UTC, clintoncwolfe commented on .expeditor/config.yml
> +     version_constraint: 6.*
We want to change the version constrain on main to be a dummy value, `99.*` or similar. We do not want to main to match anything at the moment. Main will be temporarily unreleasable until we merge a PR from the inspec-6 branch making main match 6.*

2023-08-15 19:25 UTC, clintoncwolfe commented on .github/dependabot.yml
> +  target-branch: "inspec-5"
Very good catch to configure Dependabot as well.

2023-08-15 19:25 UTC, clintoncwolfe commented on .github/dependabot.yml
> -  target-branch: "inspec-6"
At this time we are not deleting the InSpec 6 branch - that will happen in a merge.

2023-08-16 06:36 UTC, Vasu1105 commented
Thanks @clintoncwolfe !! Updated the PR as per review comments.

2023-08-16 13:41 UTC, clintoncwolfe approved these changes
Looks good - thank you. Ship it!

2023-08-16 13:41 UTC, merged