Allow the negate formating for cmp
inspec/inspec pull request #6862
Opened 2023-11-15 15:58 UTC by Taknok

## Description
The 'cmp' matcher when used with a negation as 'should_not' does has a confusion formating when control fails:
![image](https://github.com/inspec/inspec/assets/12498020/e45ac096-a37d-423e-8ad6-7e61afec8fb3)

This, because the 'format_actual' always pass 'false' to the 'format_expectation'. Thus the 'format_expectation' never reach the 'negate_str'.

When passing the negate value to the 'format_expectation' the output is more intuitive:
![image](https://github.com/inspec/inspec/assets/12498020/e25bc88f-fa9b-4514-b1af-ac46c3d31654)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)
- [x] other 

## Checklist:
- [x] I have read the **CONTRIBUTING** document.

2024-01-08 11:16 UTC, Taknok commented
I allow myself to send a message to up the topic as there was no comment since the beginning and 2 month passed.

2024-02-08 21:00 UTC, Taknok commented
Should I drop this PR ? Is this an unwanted feature ?

2024-02-09 04:28 UTC, aaronlippold approved these changes

2024-02-12 05:51 UTC, Vasu1105 requested changes
Thanks @Taknok and sorry for delay in reply.  LGTM. Could you please rebase the branch and fix the lint failures and add unit test if possible around this?

2024-02-13 12:31 UTC, Taknok commented
Hi,
I rebased my branch onto the main.
Which linting failure are you refering ? I do not see the buildkite report. The others do not show linting failures.
My modification does not impact the tests as the code was already there, the option was just not passed till the end.
On inspec/main:
![image](https://github.com/inspec/inspec/assets/12498020/5ca7de38-3315-4d84-abd0-35539fd4f378)

On taknok/main:
![image](https://github.com/inspec/inspec/assets/12498020/e378370c-bd2c-4d1b-8f20-496a7f30ae35)

2024-02-13 14:34 UTC, Vasu1105 commented on lib/matchers/matchers.rb
> +  def format_actual(actual, negate=false)
```suggestion
  def format_actual(actual, negate = false)
```

2024-02-13 14:34 UTC, Vasu1105 commented on lib/matchers/matchers.rb
> +  def format_actual(actual, negate=false)
Need this changes for fixing lint.

2024-02-14 05:43 UTC, Vasu1105 commented
@Taknok This PR also missing DCO sign off please follow the Details https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco and do the needful.

2024-02-14 20:41 UTC, Taknok commented
Push force: The linting commit has also the DCO now.

2024-02-16 07:34 UTC, Vasu1105 approved these changes
LGTM. Thanks @Taknok.

2024-02-20 09:29 UTC, merged